### ISSUE TITLE
gi_v2 branch macosx 'make test' fails due to .so not found when execute in different dir from compiled

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#102]
compiling the test executables with absolute paths to the .so made them portable on linux, but apparently not on mac. Learn about the .dylib link process on mac and fix it. Maybe rpath stuff? It would be a shame to have to make all the test execs link to .a (and become 1MB each).

Resources:
http://nickdesaulniers.github.io/blog/2016/11/20/static-and-dynamic-libraries/
older one:
https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html

**Comment by lu1and10** [comment]
let's check if commit 3e4bce8f01fc068ba27a23c84cd26f2af2a92253 fix the problem on MacOS

**Comment by ahbarnett** [comment]
well that was easy - thanks, Alex
