### ISSUE TITLE
replace clunky RESCALE with function, a tester, and check spreader handles kx[i] rounding

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#106]
Issue #103 raised need for some tidy up and detailed checking here. I hadn't looked at this since 2017.
bin_sort: if i1 etc rounds to <0 or >=N1, will crash.  - doesn't inserting a check slow it down?
Check the grid and spread when kx = -eps is passed in due to rounding errors. Much more possible now single-prec is being used.

**Comment by janden** [comment]
While we're discussing this, does it make sense to split up the folding (to make sure the frequencies are in the right interval) and the rescaling? Part of the reason we have a clunky macro is that it's tasked with doing both. Is this necessary to achieve the performance we want?

**Comment by ahbarnett** [comment]
Good to question everything! The pirange switch is purely historical - we have no other use case for spreadinterp than FINUFFT (although originally I thought it might be standalone). So, points always come in with pi-periodicity, and are folded and scaled to [0,N], which is convenient for rounding to the grid (note N is nf in finufft). Both have to happen, but sure the macro is opaque. It could be two separate inline C++ funcs - someone would have to check there's no overhead. This isn't trivial because overhead for wrapping from larger than [-3pi,3pi] did slow it down. I will try next week.

**Comment by ahbarnett** [comment]
Extensive speed testing in gi_v2_rescale branch (see devel/foldrescale*) showed that, despite what the CCQ C++ fans say, an inline function gets compiled to something quite a bit slower than a macro.  Eg, check this out, for example, in the comments of foldrescale_perf2.cpp:
This is for -Ofast which ends up not being faster in the finufft context. But in this simplified test (including binning) the func is way slower than a macro:

alex@fiona /home/alex/numerics/finufft/devel> g++-9 -O3 -funroll-loops -march=na
tive -I../include -fopenmp foldrescale_perf2.cpp -o foldrescale_perf2 -lgomp -Of
ast -fno-finite-math-only
alex@fiona /home/alex/numerics/finufft/devel> ./foldrescale_perf2
simple array sum:           	0.4 ns/call	(sum:-9554.451222028649)
simple bin over [-3pi,3pi):  	1.5 ns/call	(ans:100815)
w/ RESCALE1 macro:       	2.0 ns/call	(sum:499919136.1859143)
w/ RESCALE macro (pir=0):	6.7 ns/call	(sum:499919136.1859143)
w/ RESCALE macro (pir=1):	1.9 ns/call	(sum:499919136.1859144)
w/ foldrescale1:           	7.8 ns/call	(sum:499919136.1859144)
w/ foldrescale2:           	6.7 ns/call	(sum:499919136.1859144)
w/ foldrescale3:           	7.0 ns/call	(sum:499919136.1859144)
w/ foldrescale (pir=0):  	6.4 ns/call	(sum:499919136.1859144)
w/ foldrescale (pir=1):  	8.1 ns/call	(sum:499919136.1859143)
						(ans:904913)

So this was addressed by a cleaner macro in commit  7fd9786
