### ISSUE TITLE
Row-major ordering in many Python interface

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#111]
NumPy arrays are by default row-major ordered (or C-ordered), which means that most code is written with this in mind (last index is fastest). This doesn't matter too much for us right now (we rearrange things internally so that the C library gets the right order), and there are tricks we can use to speed things up if we get an array in the “wrong” order, like switching frequencies (I think). In other words, we're not locking ourselves in too much in terms of the interface.

Except… for the many interface calls. Right now, a call to `nufft1d1` will expect an input array of size `(M, K)`, where `M` is the number of nonuniform points and `K` is the number of transforms. Since row-major is the default convention, a more reasonable input size would be `(K, M)`. Internally, of course, we'd switch the order for the call to the C library. Same thing would apply for higher dimensions.

**Comment by ahbarnett** [comment]
I agree. But how does this work for Fourier coeff ordering?
x (N1) is fastest, through to z (N3) slowest.
Would a vectorized 3d1 output have shape (N3,N2,N1,K) ?  That seems to be logical (it is the underlying storage order, expressed in py).

We don't want unnecessary copying of data (although usually the mode coeffs array isn't as big as the NU pts arrays) - or rather it is already copied in finufft.cpp, so instead we should insert some new C++ funcs there to handle other orders - not too hard, but needs another opts flag. But that isn't needed yet I hope.

**Comment by janden** [comment]
Fourier coefficients would have `K` first, in the same way. So it'd be something like `(K, N1, N2, N3)`. Right now, we can copy it internally to the right order for the C call (for inputs and outputs). Like I said, I think there are some tricks we can play to avoid copies for row-major ordered arrays (which would make sense). The important thing right now is that we fix the interface so that we don't have to break things in the future.

**Comment by lu1and10** [comment]
Currently the code is using _cchk and _rchk functions to ensure all the
in/out data is F-ordered, I thought we agreed on this when I adopted this
from David Stein's finufft py interface.

**Comment by lu1and10** [comment]
Currently as long as np array is shape of (M,K), if it's C-continuous, we are making a copy of np array and making it F-continuous, so the code still works while we double the memory. Should we change the ntrans dimension to the first just for python? Matlab is using (M,K) ntrans is the last dimension. It seems not consistent if the order differs for different language interfaces.

**Comment by janden** [comment]
> Currently the code is using _cchk and _rchk functions to ensure all the
in/out data is F-ordered, I thought we agreed on this when I adopted this
from David Stein's finufft py interface.

We did, but this is a separate issue (I think). We can change these things around internally to make it work faster (that is, without copying) later on, but we can't change the API that easily. If the API says that the *many* dimension is the last one, this will be unnatural to NumPy users (and also wouldn't play nicely with a lot of the conventions, such as indexing and broadcasting).

To give you an idea for how this would work, we would take in an array of size `(K, M)`. Since C-contiguous is default in Python, its transpose would be F-contiguous with shape `(M, K)`, so sending the transpose to the library wouldn't involve a copy. Same thing with the output. It's F-contiguous, and would have shape `(N, K)`, we take the transpose, which is C-contiguous and give it back to the user, which sees an array of shape `(K, N)`. For higher dimensions, it gets a little complicated, because we have to switch the frequencies to make things match up. In other words, if we specify a transform of size `(N1, N2)` in Python with frequencies `x, y`, we would call the library with a transform of size `(N2, N1)` and frequencies `y, x`. This way, we would be treating C-contiguous arrays as the default in Python, but secretly thinking of them as F-contiguous *under the hood* when calling the library. No copies are necessary.

> Should we change the ntrans dimension to the first just for python? Matlab is using (M,K) ntrans is the last dimension. It seems not consistent if the order differs for different language interfaces.

Yes I think this is an acceptable divergence. Matlab is F-contiguous by default, while Python is C-contiguous by default. Other interfaces, such as to BLAS and FFTW, mimic this.

**Comment by lu1and10** [comment]
We also need to deal with the case that if the user does supply input data
as F-contiguous np array? Or do we assume all the input data from the user
must be C-contigunous otherwise we report error?
More specifically,
case 1, an user input np array of size (K, M) of C-contiguous, no copy
needed
case 2, an user input np array of size (K, M) of F-contiguous, copy needed?

**Comment by ahbarnett** [comment]
Sorry, I made an error in my prev comment. Here I say what I meant to:

Basically, py dim ordering is reversed compared to matlab & fortran.
A 3d1 many transofrm would have output (K,N3,N2,N1) in py, since it's [N1,N2,N3,K] in matlab.
This reflects the storage.

I think we should sort out F-contig arrays first, and handle them w/o copying.
If in 1d1many the input is F-contig (K,N1) this is already correct ordering, and a ptr is passed to the lib.
So, this defines the python FOurier arrays:
(K,N1) in 1d, (K,N2,N1) in 2d, (K,N3,N2,N1) in 3d.

Note if M = # NU pts, this is *never* stacked. It's just a vector so (M) and (M,) are acceptable.

I don't understand C-contig arrays so I'll leave that for you guys, but I imagine a copy is needed.

**Comment by janden** [comment]
> We also need to deal with the case that if the user does supply input data
as F-contiguous np array? Or do we assume all the input data from the user
must be C-contigunous otherwise we report error?

The default assumption should be that the data is C-contiguous. If the user supplies it in F-contiguous order, they incur a performance loss (due to copying), but that's to be expected in Python.

> case 1, an user input np array of size (K, M) of C-contiguous, no copy needed
> case 2, an user input np array of size (K, M) of F-contiguous, copy needed?

Yes so in case 2, we would make a copy.

> Basically, py dim ordering is reversed compared to matlab & fortran.
> A 3d1 many transofrm would have output (K,N3,N2,N1) in py, since it's [N1,N2,N3,K] in matlab.
> This reflects the storage.

Correct. The confusing thing is that when we specify the size to `Plan.__init__`, we would specify it as `(N3, N2, N1)`, but the wrapper would then call `finufft_makeplan` with the shape `(N1, N2, N3)`, since this is the shape in Fortran ordering (the fastest dimension has size `N1` in both cases). It would also need to reverse the frequencies, so `Plan.setpts` with arguments `x, y, z` would pass `z, y, x` to `finufft_setpts`. In `Plan.execute`, we pass the pointer if it's C-contiguous, otherwise make a copy.

> I think we should sort out F-contig arrays first, and handle them w/o copying.

I don't know that it will always be possible to have both F-contiguous *and* C-contiguous arrays handled without copying, at least not in the plan interface. (The simple interface could do it, but not in the many interface.) The reason is that we would have to know whether the frequencies need to be reversed or not (see above) and we don't know this until the array is given during `Plan.execute`. (A kludgy solution would be to store two plans, one for each order. A slightly more workable solution would be to specify F or C order when creating the plan, but that can be confusing to the user.)

When we have more than one input, it's not possible to allow both C- and F-contiguous arrays to be passed in without copy. The reason is that for F-contiguous arrays, the stacking axis (that is, the “many” index of size `K`) will be fastest, since it's the first index. There's no way to vectorize across that axis without rewriting the spreader (I think Ludvig looked at this?). If we keep it as is, and have the stacking axis be last, it will work for F-contiguous, but for C-contiguous arrays, *that* axis is the fastest. Since having the stacking axis be first is the standard convention in NumPy (since C-contiguous ordering is implicit), preferential treatment of F-contiguous arrays is not possible.

> If in 1d1many the input is F-contig (K,N1) this is already correct ordering, and a ptr is passed to the lib.
> So, this defines the python FOurier arrays:
> (K,N1) in 1d, (K,N2,N1) in 2d, (K,N3,N2,N1) in 3d.

I don't quite understand. If the array is F-contiguous and of shape `(K, N1)`, the fastest index is first, which won't work (Finufft wants the stacking axis to be slowest). For C-contiguous, we just pass the pointer.

The reason all of this is happening is because NumPy tries to be clever about these things and hide the memory layout from the user. The idea is that if you consider everything to be C-contiguous, it works out most of the time. When it doesn't, wrappers for lower-level libraries can play indexing tricks (calling Blas with transpose flags, for example) and get you the performance anyhow. (I'm fairly certain Matlab does this as well, but it doesn't expose any of it to the user.) As I mentioned, we can pull a few of those tricks too, but there are limits. The stacking axis for the many interface is one of them. If we want things to work out naturally for C-contiguous arrays, it has to come first.

**Comment by ahbarnett** [comment]
Ok, thanks. For someone trained on working with the memory layout, this is a mess. Wish you could just pass a pointer and have the user supply the right ordering of array :)
Thanks for the details!
I didn't know C-contig were given preferential treatment in numpy. I thought both were options.

When I listed the py sizes (K,N1) in 1d, etc, this was using the standard python ordering of (slowest,...,fastest).  I didn't realize that changed if you called it "F-contig". So, in which case, my statement
_So, this defines the python FOurier arrays:
(K,N1) in 1d, (K,N2,N1) in 2d, (K,N3,N2,N1) in 3d._
applies to C-contig arrays.

The reversing of the (z,y,x) I guess is a neat way to avoid a final transpose operation. 

Maybe you should have David S chime in, since he's been doing (NU)FFT py for a while... A

**Comment by lu1and10** [comment]
I see, this is not hard.
We just need to reverse the dimension ordering for the input/output array
for python users, change _cchk and _rchk to enforce C-contiguous instead of
F-contiguous.

**Comment by lu1and10** [comment]
Just emailed David, I guess we should wait for David's opinion before
changing the array dimension order for python.

**Comment by lu1and10** [comment]
BTW, the master branch python interface is using the same ordering(n_trans
as the last dimension) as the matlab interface.
This array dimension ordering change may affect current python users.
But as Joakim says, if we want to change the interfaces we'd better change
earlier than later.

**Comment by janden** [comment]
I believe this is now fixed.
