### ISSUE TITLE
Simple Python interface fails for real inputs

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#113]
Right now, this fails
```
import numpy as np
import finufftpy

xy = 2 * np.pi * np.random.uniform(size=(2, 16))
f = np.random.standard_normal(size=(8, 8))

c = finufftpy.nufft2d2(xy[0], xy[1], f)
```
We should check whether the input is complex and cast if not.

**Comment by ahbarnett** [comment]
Good catch.

**Comment by lu1and10** [comment]
Currently the code checks the f, if f is not complex128 for double prec or
complex64 for single prec it will give a runtime error message to the user
to input a complex type data. We can change to make a copy of real and
convert to complex.

**Comment by lu1and10** [comment]
fixed in commit 0499c82b3eb354fac3147c34ef37bd2e8e9a2ed3 of branch gi_v2_nthr, it should resolve the issue for guruInterface_v2 branch too when merged.

**Comment by janden** [comment]
Thanks. It's not 100% clear to me, but I assume this fixes all types and dimensions?

**Comment by lu1and10** [comment]
I added the support for real input casting to the complex in
commit 0499c82b3eb354fac3147c34ef37bd2e8e9a2ed3 of branch gi_v2_nthr. It
should work with real input now.

**Comment by janden** [comment]
This is fixed.
