### ISSUE TITLE
Python simple interface keyword dtype support

### ISSUE THREAD

**Issue by lu1and10** [flatironinstitute/finufft#116]
Currently for simple interfaces,
If one wants to do double precision calculation,
one should call simple interface for type 1 as,
finufftpy.nufft1d1(x, c, N)
if one wants to perform single precision calculation,
it should be called as,
finufftpy.nufft1d1(x, c, N, dtype='single').

dtype='single' or 'double' is supported in Plan constructor.
Do we need to support dtype='single' for simple interfaces? or we infer the precision dtype from x.dtype?

**Comment by janden** [comment]
Yeah we should remove the `dtype` kwarg from the simple interfaces. It's only needed for the plan. For the simple interfaces, we infer it from the input array.

**Comment by lu1and10** [comment]
fixed in commit 0a39621147b19f96cea6f8282215192d43b09584 of branch
gi_v2_nthr. Let's check.

**Comment by janden** [comment]
I think this is done.

**Comment by ahbarnett** [comment]
thanks.
