### ISSUE TITLE
2d type-2 or type-1 has transpose of expected for python interfaces

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#12]
David S claims 2d1 followed by 2d2 on regular NU pts results in transpose, driving from python.
Check the fast,slow orderings in numpy arrays.

**Comment by penfe** [comment]
@ahbarnett Hi Barnett, 

I finufft2d1 followed by finufft2d2 (c++, -DSINGLE and master branch), the restored image is reversed in both horizontal and vertical direction.
Would you please show me if I missed somthing? Thanks in advance.

...

finufft_default_opts(&m_opts);// m_opts share to both finufft2d1 and finufft2d2

finufft2d2(m_read * m_spokes, const_cast<float*>(m_x), const_cast<float*>(m_y), ksp, m_iflag, m_acc, m_rows, m_cols, const_cast<std::complex<float>*>(img), m_opts);

finufft2d1(m_read * m_spokes, const_cast<float*>(m_x), const_cast<float*>(m_y), const_cast<std::complex<float>*>(ksp), m_iflag, m_acc, m_rows, m_cols, img, m_opts);

![err](https://user-images.githubusercontent.com/181877/78205969-24f0c580-74d0-11ea-9f10-09de3440ab03.png)

**Comment by ahbarnett** [comment]
Dear Penfe,
I think this is a different issue from the one listed here (which involves x<->y flipping for python users).
For you: just flip the sign of m_iflag in your 2d1 to make it the transpose (but not inverse!) of the 2d2. Let me know if that works.
Best, Alex

**Comment by penfe** [comment]
> 
> 
> Dear Penfe,
> I think this is a different issue from the one listed here (which involves x<->y flipping for python users).
> For you: just flip the sign of m_iflag in your 2d1 to make it the transpose (but not inverse!) of the 2d2. Let me know if that works.
> Best, Alex

Thanks Alex very much! It works.

**Comment by ahbarnett** [comment]
The new py interfaces get this right, as of v2.0.0.
