### ISSUE TITLE
Make `make python` install in editable/development mode

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#150]
This would bring the `python` target in line with the others in that it will only result in changes to the project directory (no install). The examples should be run either by making sure that the `finufft` package is in the working directory or by modifying `PYTHONPATH` appropriately.

**Comment by ahbarnett** [comment]
makefile already has $(FINUFFT) as abs path available.
Let's kill FINUFFT_DIR
kill dotenv, and pybind11

**Comment by ahbarnett** [comment]
I will update docs so py in osx is recommended as : pip install finufft
Separate section at bottom on locally building.

**Comment by ahbarnett** [comment]
12a548e I reorganized install docs. We can update the python ones when closing this Issue.
Have fun w/ the cleaner make python, and thanks! Alex

**Comment by janden** [comment]
So I've been looking around, and there seems to be no good way of building a Python package locally without installing it. Running `setup.py build` will do that, but it'll put it in a location with a platform dependent name `build/lib.linux-x86_64-3.8` for me, so we'd have to parse that and add it to the `PYTHONPATH` to get anything to run, which is not ideal.

I suggest we stick with what we have (run `pip install` to install the module somewhere), despite the potential problems of “installing” a package that depends on a certain dynamic library staying in the project directory. A compromise might be to install the package in “editable” or “development” mode (using `pip install -e` or `python setup.py develop`), which won't copy any of the Python sources into `site-packages`, but just create a link to the existing Python source files in the project folder. This will make it clear that the code that's running is the one in the project directory and reduce the potential for disconnect.

Regarding your Ubuntu crash, it sounds like what I'm experiencing on my machine. I managed to put in a workaround in `setup.py` and will push that to a new PR.

**Comment by ahbarnett** [comment]
cool. sorry, just found this.
FWIW, dfm's py code does exactly the pip install -e thing. Might be a good model for the 3 ways to install:
https://docs.exoplanet.codes/en/stable/user/install/

**Comment by ahbarnett** [comment]
Of course, I just tried adding the -e flag in the makefile and it builds ok, but fails to find the finufftc module upon import finufft, now!
So, I'll leave this for someone else.
You probably don't need the output (ubuntu 16.04, py3.7):
```
(idp) alex@fiona /home/alex/numerics/finufft> python python/test/run_accuracy_tests.py 
Traceback (most recent call last):
  File "/home/alex/numerics/finufft/python/finufft/_finufft.py", line 50, in <module>
    fh = imp.find_module('finufft/finufftc')[0]
  File "/home/alex/miniconda3/envs/idp/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'finufft/finufftc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/test/run_accuracy_tests.py", line 1, in <module>
    from accuracy_speed_tests import accuracy_speed_tests
  File "/home/alex/numerics/finufft/python/test/accuracy_speed_tests.py", line 8, in <module>
    import finufft
  File "/home/alex/numerics/finufft/python/finufft/__init__.py", line 15, in <module>
    from finufft._interfaces import Plan
  File "/home/alex/numerics/finufft/python/finufft/_interfaces.py", line 20, in <module>
    import finufft._finufft as _finufft
  File "/home/alex/numerics/finufft/python/finufft/_finufft.py", line 59, in <module>
    raise RuntimeError('Failed to find a suitable finufft library')
RuntimeError: Failed to find a suitable finufft library
```

**Comment by janden** [comment]
Ok. I'll see if I can get `pip install -e` to work. That would be ideal “installation” for development work (you don't have to run `pip install` each time you modify the source).
