### ISSUE TITLE
`finufftc` Python module does not link to `libfinufft.so`

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#151]
On certain systems (Ubuntu 20.04), `finufftc` will not point to the proper `libfinufft.so` since there is no function in the source pointing to it. As a result, we're not able to load the library.

There might be a way to fix this by adding a short dummy source which calls a function in `libfinufft.so` to force a link.

**Comment by ahbarnett** [comment]
Ok, your other stuff is in master. Have fun w/ fixing this linking issue :)

PS do we really need a finufftc dummy module name at all?

**Comment by janden** [comment]
> PS do we really need a finufftc dummy module name at all?

Yes. For two reasons:

- If we don't have the `finufftc` dummy module, installation by `make python` will work, but to run any Python code which imports the `finufft._finufft` module, we have to make sure that `LD_LIBRARY_PATH` is set to point to `libfinufft.so`. What the `finufftc` module does is encode the absolute path to `libfinufft.so`. This way, `finufft._finufft` can find the `finufftc` library and load it, which in turn loads `libfinufft.so`.
- When we build the binary wheel, we need some way to tell `pip` that we depend on an external dynamic library (`libfinufft.so`). It can't know this by looking at the code since we only load that library at runtime. By including a dummy module that links to `libfinufft.so`, we make it clear that we depend on that library. As a result, the `audit_wheel` command will find that library and package it in the wheel.

**Comment by ahbarnett** [comment]
fixed by #153
