### ISSUE TITLE
`wheel` target in Makefile

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#152]
What does this do? I tried running it and it appears to use `delocate-wheel`, which is a macOS specific tool. Is this target only needed for macOS? It may make sense to rename it in that case.

**Comment by lu1and10** [comment]
Yes, this is only for Mac. So I guess rename `wheel` to `mac-wheel` should be more reasonable.

**Comment by janden** [comment]
Ah. Does that not need to run in Docker? Seems like it would be less risky when it comes to compatibility of the wheels.

**Comment by lu1and10** [comment]
For me, I just run this mac wheel maker(`make wheel`) in the python virtual
environment, no need to use Docker.

**Comment by janden** [comment]
Right, but the dynamic library set up might be different on your laptop compared to a standard macOS install. This is of course less of an issue compared to Linux (which is why `manylinux` is crucial there), but could still create problems, I think.

**Comment by lu1and10** [comment]
Yes, you are right, this may cause problem when linking with finufft
dynamic library.
This was used when we were using pybind11 and the pybind11 extension module
was linking lib-static/libfinufft.a, now we switch to using dynamic library.

**Comment by ahbarnett** [comment]
if it is useful for devs, leave it in the makefile, and document it.
If not, remove since dead code.
thx, A

**Comment by ahbarnett** [comment]
@lu1and10   Hi Libin, could you act on the above based on how CI and mac wheels is shaping up? Thanks, Alex

**Comment by ahbarnett** [comment]
@lu1and10 please see Oct 8 2020 request to clean this up - thanks! Alex

**Comment by ahbarnett** [comment]
@lu1and10 can you decide if this issue is still relevant or can be closed? Thx.
