### ISSUE TITLE
Ineffective OpenMP pragmas?

### ISSUE THREAD

**Issue by mreineck** [flatironinstitute/finufft#159]
While debugging another issue, I encountered OpenMP pragmas in `spreadinterp.cc`, which look a bit strange.
One example is line 1156
```
#pragma omp parallel for num_threads(nt) schedule(dynamic,10000) // matters
    for (int t=0; t<nt; ++t)
      for (BIGINT b=0; b<nbins; ++b)
	counts[b] += ct[t][b];
```

Unless `nt` is larger than 10000 (which seems improbable), this construct is not parallelized at all. Is it possible that the loops over `b` and `t` should be exchanged?

(Actually, if this loop were actually parallelized by setting the chunk size to 1, the result would be undefined because of concurrent writes.)

This construct occurs in a few places throughout the code. I don't think that it affects overall performance very much, however, since the loops in question should not be dominant.

**Comment by ahbarnett** [comment]
Thank-you for catching that! Indeed in my tests, loop order, and multithreading made no difference in these two operatiions - they should be very much DRAM-speed limited.
