### ISSUE TITLE
pip install doesn't install dependencies (NumPy)

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#162]
(We discussed this during the meeting on 2020-10-12.) When you run `pip install finufft`, it should install our dependencies (`numpy`) but it currently does not. When I download the wheel, inside the `METADATA` file, we see that indeed the `Requires-Dist` tag is missing. However, when I try to reproduce this on the current `master`, I don't observe this behavior. In other words, I do see `Requires-Dist: numpy` in `METADATA` and when I run `pip install` from the resulting wheels, it auto-installs `numpy`.

It looks like this issue is solved, but it's hard to know without knowing what's caused it. Before we upload 2.0.1 to PyPI, I suggest we put it on test.pypi.org and try installing it on a clean venv to make sure `numpy` is properly installed as a dependency.

**Comment by janden** [comment]
For what it's worth, I also tried this with what I assume was the commit used for the PyPI upload (9cad445). Same result there. (`Requires-Dist: numpy` in `METADATA` and `pip install` also installs `numpy`, as desired.)

**Comment by ahbarnett** [comment]
As the python nonuser here, can I leave you, Libin and Garrett to test this one?

**Comment by janden** [comment]
Doesn't seem to come up anymore (running `pip install finufft` in a fresh venv installs numpy). Closing.
