### ISSUE TITLE
yum install fftw3-devel in Dockerfile

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#163]
(Another thing we discussed at the meeting on 2020-10-12.) I tried replacing the manual compilation of FFTW in the Dockerfile with a call to `yum install fftw3-devel`). As @lu1and10 pointed out, this fails. The reason is that since we're compiling for the `manylinux2010` platform, which is based on CentOS 6, it installs the latest version of FFTW available at the time (2010), which is FFTW 3.2.1. As a result, the code doesn't compile, since we use the newfangled `fftw_alloc_complex` instead of good old `fftw_malloc`. If we fix that, we run into a larger problem: OpenMP support was introduced in 3.3. We need that.

A potential way out is to upgrade to manylinux2014 (a reasonable option, but will leave certain users with older systems without an installable package). This will install the (less ancient) FFTW 3.3.3, which has OpenMP support (and `fftw_alloc_complex`). The other (I think better) option is to leave things as @lu1and10 has written it, which is to install FFTW 3.3.8 from source, but add a short comment explaining why this is necessary and suggesting we switch to `yum install fftw3-devel` when we upgrade to `manylinux2014`. (CentOS 6, and therefore also manylinux2010, will go EOL on [November 30th, 2020](https://web.archive.org/web/20180108090257/https://wiki.centos.org/About/Product), so this may be in the cards for version 2.1.)

**Comment by ahbarnett** [comment]
Return to in Dec 2020.

**Comment by janden** [comment]
The Dockerfile in `python/ci/docker` doesn't seem to be used anymore to build the wheels, so I think this issue can be closed.
