### ISSUE TITLE
Uncalled functions

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#164]
These functions do not appear to be called in the course of `make test` and `make examples`:

- `spreadinterp.cpp:spreadinterp`
- `spreadinterp.cpp:evaluate_kernel_noexp`
- `spreadinterp.cpp:set_kernel_args`
- `spreadinterp.cpp:evaluate_kernel_vector`
- `utils.cpp:errtwonorm`
- `utils.cpp:indexedarrayrange`
- `utils_precindep.cpp:get_num_threads_parallel_block`

Some of these (notably the ones in `spreadinterp.cpp`) probably have to do with certain kernel evaluation methods not being tested. If we want to keep those methods, it would make sense to extend tests to cover them. For other functions, though, it might be better to remove them.

**Comment by ahbarnett** [comment]
I have tidied the docs. spreadinterp() *is* needed for ``make spreadtest`` (hence ``make perftest``) which is useful for developers.
I suggest that ``make spreadtest`` task is added to CI.

I will get to the kernel and utils stuff shortly.

**Comment by ahbarnett** [comment]
I don't see where the CI list of executables to run is, but here are some ones to add that address the above spreadtest, and check 

compile perftest/spreadtestnd and perftest/spreadtestndf as in the makefile, then:
# checks default ppval kernel:
perftest/spreadtestnd 1 1e6 1e6 1e-6
perftest/spreadtestnd 2 1e6 1e6 1e-6
perftest/spreadtestnd 3 1e6 1e6 1e-6
perftest/spreadtestndf 1 1e6 1e6 1e-3
perftest/spreadtestndf 2 1e6 1e6 1e-3
perftest/spreadtestndf 3 1e6 1e6 1e-3

# checks kerevalmeth=0 w/ nonstandard upsampfac:
perftest/spreadtestnd 1 1e6 1e6 1e-6 2 0 0 0 0 1.5
perftest/spreadtestnd 2 1e6 1e6 1e-6 2 0 0 0 0 1.5
perftest/spreadtestnd 3 1e6 1e6 1e-6 2 0 0 0 0 1.5
perftest/spreadtestndf 1 1e6 1e6 1e-3 2 0 0 0 0 1.5
perftest/spreadtestndf 2 1e6 1e6 1e-3 2 0 0 0 0 1.5
perftest/spreadtestndf 3 1e6 1e6 1e-3 2 0 0 0 0 1.5

Can someone add this to CI? Then it covers all of spreadinterp functions apart from eval_kernel_noexp.

**Comment by janden** [comment]
I see. I wasn't talking about a specific CI test suite, just running `make test` and `make examples` locally. I'll see what coverage looks like when I also run `make spreadtest`. Why is this using `spreadinterp` and not `spreadinterpSorted`?

**Comment by ahbarnett** [comment]
commits 502f090 eac7f48 a8ab1c0 remove obsolete functions or test untested ones.

spreadtestnd.cpp uses the original interface which was spreadinterp(). But finufft.cpp v2.0 (since it can do batching) splits out the sorting from spread/interp, hence only accesses lower-level funcs.  But I like also maintaining the simpler "reference implementation" spreadinterp(), since it shows how to use these lower-level funcs, without the complication of batching.

I now added a replacement task, ``make spreadtestall`` which hits the needed tests - please use that instead of ``make spreadtest``.
This can be appended to ``make test`` and ``make examples``

**Comment by janden** [comment]
> But I like also maintaining the simpler "reference implementation" spreadinterp(), since it shows how to use these lower-level funcs, without the complication of batching.

I guess my question would be why that needs to live in the main code if it's only used for testing. That reference code could effectively be moved to the tests.
