### ISSUE TITLE
Allocated memory is growing when finufft1d3 is used in a loop

### ISSUE THREAD

**Issue by martinzonda** [flatironinstitute/finufft#170]
Hi!

I have a strange problem with the fortran interface which I can reproduce using a slightly modified example nufft1d_demo.f found in fortran/examples/

If finufft1d3 is placed in a long loop, e.g.

do j = 1,500000
        call finufft1d3(nj,xj,cj,iflag,eps, ms,sk,fk1,null,ier)
end do

the taken memory is increasing at each repetition. As if a new array was always allocated but not disallocated. 
The finufft1d1 and finufft1d2 don't have this problem.

Used compiler and lib.:
gfortran 8
gcc version 8.3.0 (Debian 8.3.0-6)
libstdc++.so.6
libfftw3.so.3

Can you tell me whats going on?

Best,
Martin

**Comment by lu1and10** [comment]
@ahbarnett In "src/finufft.cpp",  it seems p->X, p->Y and p->Z allocated around line 807-814 and p->sortIndices allocated on line 898 are not freed in destroy.

Should we change t3 destroy from:

"""
    if (p->innerT2plan)
      FINUFFT_DESTROY(p->innerT2plan);
    free(p->CpBatch);
    free(p->Sp); free(p->Tp); free(p->Up);
    free(p->prephase);
    free(p->deconv);
"""

to:

"""
    if (p->innerT2plan)
      FINUFFT_DESTROY(p->innerT2plan);
    free(p->CpBatch);
    free(p->Sp); free(p->Tp); free(p->Up);
    **free(p->X); free(p->Y); free(p->Z);**
    free(p->prephase);
    free(p->deconv);
    **free(p->sortIndices);**
"""

**Comment by ahbarnett** [comment]
Thank-you for finding these Libin - you are right! My bad. And thank-you for raising the issue - I had not done such extensive t3 tests with repeated plans. Fixed by 2ff3d4e

**Comment by ahbarnett** [comment]
@martinzonda thanks for catching this. Please let us know if this did not fix it. Also, if you do do repeated calls, check out the guru interface since it is designed for such cases when the points don't change but the strengths or coeffs do. Best, Alex
