### ISSUE TITLE
Is calling FINUFFT from OpenMP parallelized region supported?

### ISSUE THREAD

**Issue by gzauhar** [flatironinstitute/finufft#183]
Hi there,
I am wondering is my use case supported by FINUFFT or not?
My use case is: calling `finufft2d3()` from already OpenMP parallelized region. If it is supported then I have found at least two issues. First issue is `bin_sort_multithread()` fails to sort (there is simple workaround) but I haven't debugged second issue.

I have manged to reproduce exactly the same issue I am hitting by slightly modifying `finufft2d_test.cpp`. Essentially I am calling `finufft2d3()` from OpenMP parallelized region. Bellow is the patch, please apply it on top of master (commit 95665118) and don't forget to enable `FFTW_PLAN_SAFE` (I am using FFTW-3.3.4 so I have to manually synchronizing access to FFTW functions with `std::mutex` and `std::lock_guard`).

```c++
Author: Goran Žauhar <gz@ticra.com>
Date:   Fri Apr 16 12:54:58 2021 +0200

    Repro

diff --git a/makefile b/makefile
index f745f87..8cc9790 100644
--- a/makefile
+++ b/makefile
@@ -26,7 +26,7 @@ PYTHON = python3
 # Notes: 1) -Ofast breaks isfinite() & isnan(), so use -O3 which now is as fast
 #        2) -fcx-limited-range for fortran-speed complex arith in C++
 #        3) we use simply-expanded (:=) makefile variables, otherwise confusing
-CFLAGS := -O3 -funroll-loops -march=native -fcx-limited-range
+CFLAGS := -O3 -g -funroll-loops -march=native -fcx-limited-range
 FFLAGS := $(CFLAGS)
 CXXFLAGS := $(CFLAGS)
 # put this in your make.inc if you have FFTW>=3.3.5 and want thread-safe use...
diff --git a/test/finufft2d_test.cpp b/test/finufft2d_test.cpp
index fd683ec..c4ca1fa 100644
--- a/test/finufft2d_test.cpp
+++ b/test/finufft2d_test.cpp
@@ -145,11 +145,15 @@ int main(int argc, char* argv[])
     }
   }
   timer.restart();
-  ier = FINUFFT2D3(M,x,y,c,isign,tol,N,s,t,F,&opts);
+#pragma omp parallel
+{
+  CPX* Fp = (CPX*)malloc(sizeof(CPX)*N);   // mode ampls
+  ier = FINUFFT2D3(M,x,y,c,isign,tol,N,s,t,Fp,&opts);
+
   ti=timer.elapsedsec();
   if (ier>1) {
     printf("error (ier=%d)!\n",ier);
-    return ier;
+//    return ier;
   } else
     printf("\t%lld NU to %lld NU in %.3g s         \t%.3g tot NU pts/s\n",(long long)M,(long long)N,ti,(M+N)/ti);
 
@@ -173,7 +177,8 @@ int main(int argc, char* argv[])
     //cout<<"s t, F, Ft, F/Ft:\n"; for (int k=0;k<N;++k) cout<<s[k]<<" "<<t[k]<<", "<<F[k]<<",\t"<<Ft[k]<<",\t"<<F[k]/Ft[k]<<endl;
     free(Ft);
   }
-
+  free(Fp);
+}
   free(x); free(y); free(c); free(F); free(s); free(t);
   return (errmax>errfail);
 }
```
Crash happens in `spreadinterp.cpp:375`
```
Thread 37 "finufft2d_test" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff25b6640 (LWP 907056)]
0x00007ffff7f86bf8 in spreadSorted () at src/spreadinterp.cpp:375
375	          kx0[j]=FOLDRESCALE(kx[kk],N1,opts.pirange);
```
but the real reason is `bin_sort_multithread()` fails to sort.

Compiling FINUFFT without OpenMP would solve this problem but in my case it is not the solution because in my application  FINUFFT is sometimes called from parallel region and sometimes not.

**Comment by ahbarnett** [comment]
Hi Goran,
If you set `opts.nthreads=1` then internally FINUFFT will not multithread (and this includes the binsort), and you should be able to call it within an omp par block. This assumes you did FFTW_PLAN_SAFE (and, BTW I don't understand jonas-kr's comment on that exactly either!).
I notice in your `finufft2d_test.cpp` there are several variables allocated outside the omp block which I think would collide. I see you allocated `Fp` locally, but I'm referring to, eg, `ier`, that is written to by all thread, and could cause segfault. It still segfaults for me even with nthreads=1.
I could set up a simple example myself of what you're trying to do.
Best, Alex

**Comment by ahbarnett** [comment]
Hi Goran, I closed this, since to answer your question: yes it is supported, as long as you use FFTW>=3.3.6.  I have added a new example to show this in 4083eca. Any prior version of FFTW, as you use, is not supported, but you should be able to hack it yourself, by replacing the fftw_make_planner_thread_safe() with your own mutex.... not my idea of fun, but let me know how goes.
Thanks, Alex
