### ISSUE TITLE
[bug report] unintended copy of outputs

### ISSUE THREAD

**Issue by tianrluo** [flatironinstitute/finufft#192]
python version 3.7.10
numpy version 1.20.2

`np.ndarray.data` seems not to be a good choice for assessing if two `np.ndarray` objects refer to the same memory.

```python
import numpy as np

shape = (3, 3)

x = np.random.rand(*shape) + 1j*np.random.rand(*shape)
y = np.array(x, dtype=np.complex128, order='C', copy=False)

print(f'y is x: {y is x}')  # outputs `True`
print(f'y.data == x.data: {y.data == x.data}')  # outputs `False`
```

This nuance can affect the intended behavior of `finufft._interfaces._copy()`:
https://github.com/flatironinstitute/finufft/blob/2ea0fe3b11cf5380cda0c29181ec4d8398dd463a/python/finufft/_interfaces.py#L345

The 'y' in the code-block above is created following `finufft._intefaces._cchk()`:
https://github.com/flatironinstitute/finufft/blob/2ea0fe3b11cf5380cda0c29181ec4d8398dd463a/python/finufft/_interfaces.py#L318
For assessing contiguity, maybe one can also do:

```python
import numpy as np

shape = (3, 3)

x = np.random.rand(*shape) + 1j*np.random.rand(*shape)

print(f'x.data.c_contiguous: {x.data.c_contiguous}')
print(f"x.flags['C_CONTIGUOUS'] {x.flags['C_CONTIGUOUS']}")

# make copy if not `c_contiguous`
y = x if x.flags['C_CONTIGUOUS'] else np.array(x, dtype=np.complex128, order='C')
```

**Comment by ahbarnett** [comment]
Interesting point! Your little demo also outputs True and False on my python 3.7.7 and numpy 1.17.5.
I am not a python expert. I'm looping in @janden and @dbstein who are:

Are you saying that there are two issues:

1) the use of .data in the if statement on line 349. You have made a convincing demo this needs to be fixed. Do you know a more reliable way to check it, ie, are you proposing the use of "is" here?

2) in addition we should use the x.data.c_contiguous in the check in the functions _rchk, _cchk, _rchkf, _cchkf  ? That is easy to add.

Thanks for clarifying, Best,  Alex

**Comment by tianrluo** [comment]
Yes, there are two parts:

1.  Consider python variable name as an alias that refers to a certain block in the memory, then `is` should be used for checking whether two aliases are referring to the same memory. [https://stackoverflow.com/a/133024](https://stackoverflow.com/a/133024)

2. For the purpose of checking contiguity, `x.flags['C_CONTIGUOUS']` is probably a better API. [https://stackoverflow.com/a/51304155](https://stackoverflow.com/a/51304155)

**Comment by lu1and10** [comment]
> Yes, there are two parts:
> 
> 1. Consider python variable name as an alias that refers to a certain block in the memory, then `is` should be used for checking whether two aliases are referring to the same memory. https://stackoverflow.com/a/133024
> 2. For the purpose of checking contiguity, `x.flags['C_CONTIGUOUS']` is probably a better API. https://stackoverflow.com/a/51304155


@tianrluo @ahbarnett 

I'm a bit confused about `data` usage, the following code with complex128 prints x.data == x.data to be false.
`
import numpy as np
shape = (3, 3)
x = np.random.rand(*shape) + 1j*np.random.rand(*shape)
print(f'x.data == x.data: {x.data == x.data}')  # outputs `False`
`

while the following code with float64 prints x.data == x.data to be true.

`
import numpy as np
shape = (3, 3)
x = np.random.rand(*shape)
print(f'x.data == x.data: {x.data == x.data}')  # outputs `True`
`

Any ideas?

**Comment by lu1and10** [comment]
> > Yes, there are two parts:
> > 
> > 1. Consider python variable name as an alias that refers to a certain block in the memory, then `is` should be used for checking whether two aliases are referring to the same memory. https://stackoverflow.com/a/133024
> > 2. For the purpose of checking contiguity, `x.flags['C_CONTIGUOUS']` is probably a better API. https://stackoverflow.com/a/51304155
> 
> @tianrluo @ahbarnett
> 
> I'm a bit confused about `data` usage, the following code with complex128 prints x.data == x.data to be false.
> 
> ```
> import numpy as np
> shape = (3, 3)
> x = np.random.rand(*shape) + 1j*np.random.rand(*shape)
> print(f'x.data == x.data: {x.data == x.data}')  # outputs `False`
> ```
> 
> while the following code with float64 prints x.data == x.data to be true.
> 
> ```
> import numpy as np
> shape = (3, 3)
> x = np.random.rand(*shape)
> print(f'x.data == x.data: {x.data == x.data}')  # outputs `True`
> ```
> 
> Any ideas?

Trying to understand memoryview, the following link may help
https://docs.python.org/3/library/stdtypes.html#memoryview

**Comment by tianrluo** [comment]
I tend to think you have found a bug of `ndarray.data`, and you might want to report it to `numpy` devs, since the attribute behavior is quite inconsistent.

About this issue:
I think `ndarray.data` does not fit the purpose of assessing whether two `ndarray` instances are the same one in memory;
In the meantime, for the purpose of determining if an `ndarray` is `c` contiguous, directly checking the flags might be for favorable.

**Comment by lu1and10** [comment]
> I guess you have found a bug of `ndarray.data`, and you might want to report it to `numpy` devs, since the attribute behavior is quite inconsistent in your example.
> 
> About this issue: I think `ndarray.data` does not fit the purpose of assessing whether two `ndarray` instances are the same one in memory; In the meantime, for the purpose of determining if an `ndarray` is `c` contiguous, directly checking the flags might be for favorable.

Thanks. I switch to use `is` instead of `data` and the `c` contiguous flag is used in the commit c9ab156f97f52e62830b0544a4fe9f662263eebc and commit a6a9913ad19d7d718a9fea3e591f3346db7e141d

While the inconsistent behavior of `ndarray.data` for complex and float is still confusing.

**Comment by ahbarnett** [comment]
Hi @lu1and10  - it's 6 months later so can this issue be closed now - or is it hanging on some numpy bug? Would be good to avoid unnecessary array copies, but it's better to just be robust. Cheers, Alex
