### ISSUE TITLE
np.int deprecation warning coming from _interfaces.py 

### ISSUE THREAD

**Issue by sdrastro** [flatironinstitute/finufft#198]
python version: 3.8.12
numpy version: 1.20.1

Having just updated my Anaconda python installation, I now get np.int deprecation warnings every time I call nufft1d3. I use  nufft1d3 in an application that includes bootstrapping, so with tens of thousands of calls to nufft1d3 resulting in tens of thousands of deprecation warnings, my jupyter notebooks have gotten pretty ugly.

Minimal working example:

```
import numpy as np
from finufft import nufft1d3

t = np.sort(np.random.uniform(size=512))
x = np.random.normal(size=512)

fn = 1 / np.median(np.diff(t))
fgrid = np.linspace(0, fn, num=512, endpoint=True)

xtilde = nufft1d3(2*np.pi*t, x, fgrid, isign=-1, nthreads=1)
```

Output:

/Users/sdr/opt/anaconda3/lib/python3.8/site-packages/finufft/_interfaces.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  npdim = np.asarray(n_modes_or_dim, dtype=np.int)

Thanks for looking into the issue.

**Comment by lu1and10** [comment]
Hi,

the `np.int` warning has been fixed in the commit 2d049d9ff22627b6a1f105a1900f29fb7c2c8de6. You could try to install the newest version of finufft, let us know if the warning still appears.

**Comment by sdrastro** [comment]
Thank you for looking into the problem. I reinstalled finufft with
```
pip install --force-reinstall --no-cache-dir finufft
```
but unfortunately I'm still getting the deprecation warning.

**Comment by lu1and10** [comment]
﻿Could you post your entire warning log? I don’t see any np.int used in the latest _interface.py on finufft GitHub source.

Also you could check your local /Users/sdr/opt/anaconda3/lib/python3.8/site-packages/finufft/_interfaces.py to see if you really have the latest finufft version installed.

**Comment by lu1and10** [comment]
also you may check `pip list` to see the finufft version installed, the latest version is finufft 2.0.3.post1

**Comment by sdrastro** [comment]
Okay, pip list tells me I have finufft version 2.0.0, installed this morning. I'll get the latest source code from github.

**Comment by lu1and10** [comment]
I see. It depends on the OS you are using, the current pip has the
precompiled finufft binaries for the OSs in the following link,
https://pypi.org/project/finufft/#files
Other than those precompiled binary files, you may have to install from
source.
