### ISSUE TITLE
Pip wheels for 2.0.4

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#201]
Looks like the wheels on PyPI (https://pypi.org/project/finufft/) are still v2.0.3. @lu1and10 could you upload the new wheels?

**Comment by lu1and10** [comment]
Hi Joakim,

I just uploaded to PyPI, thanks!

**Comment by ahbarnett** [comment]
Hi Libin, thanks. Can you close the issue now, if that's done? Best, Alex

**Comment by lu1and10** [comment]
> Hi Libin, thanks. Can you close the issue now, if that's done? Best, Alex

Sure, closed.

**Comment by janden** [comment]
Thanks!
