### ISSUE TITLE
Error in 3D type 2

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#202]
When the latest version (2.0.4) was tested as part of our CI in ASPIRE, the tests related to 3D type 2 in Finufft failed. The following example reproduces the bug:

```python
import numpy as np

from finufft import Plan

np.random.seed(0)

shape = (8, 8, 8)
n_pts = 4
dtype = 'float32'
dtype_complex = 'complex64'

x = np.random.randn(*shape).astype(dtype)
pts = 2 * np.pi * (np.random.rand(len(shape), n_pts).astype(dtype) - 0.5)

eps = np.finfo(dtype).eps

plan = Plan(nufft_type=2, n_modes_or_dim=shape, eps=eps, n_trans=1,
        dtype=dtype)

plan.setpts(*pts)

result = plan.execute(x)

grid = np.mgrid[-shape[0] // 2:shape[0] // 2, -shape[1] // 2:shape[1] // 2,
        -shape[2] // 2:shape[2] // 2]

result_ref = np.empty(n_pts, dtype=dtype_complex)

for k in range(n_pts):
    result_ref[k] = np.sum(x * np.exp(-1j * (grid[0] * pts[0, k] + grid[1] *
        pts[1, k] + grid[2] * pts[2, k])))

err = np.max(np.abs(result - result_ref))

print(f"{err=}")
```

With a clean py38 venv, version 2.0.3 gives about `1e-4` while version 2.0.4 gives about `1e28` or `nan`.

**Comment by garrettwrong** [comment]
It is the changes in, `python/finufft/_interfaces.py`. I think I see it; will report back.

**Comment by garrettwrong** [comment]
Yeah, looks like `_cchkf` is broken for `np.float32`.  I don't really understand why they were updated.. but I can propose a patch in a few.

**Comment by lu1and10** [comment]
> Yeah, looks like `_cchkf` is broken for `np.float32`. I don't really understand why they were updated.. but I can propose a patch in a few.

Hi Garrett, I think it is related to issue 192 https://github.com/flatironinstitute/finufft/issues/192
I tried to address issue 192, it seams the copy=false matters?

**Comment by garrettwrong** [comment]
Hey, Libin, there are a few things happening simultaneously.  Specifically dtypes, ordering, and contiguousness (contiguity? :D).

Anyway, all three need to be correct to pass by a pointer...

The 2.0.4 code checked contiguousness and order, but potentially passed through the wrong dtype for the complex checkers.

The old code forced the order and dtype. I'm not sure if it would catch contiguousness... that was probably the issue with 192. That could be bad (junk or seg faults). OTOH  Copy=True would always copy and yield a c_contiguous array of the right dtype... its just expensive.  Copy=False was meant to avoid an unneeded copy.... Again it might not have been catching the non contiguous case...

Hope that helps.
