### ISSUE TITLE
NaN values returned when used in conjunction with cython

### ISSUE THREAD

**Issue by aaron-shih** [flatironinstitute/finufft#212]
I have been able to successfully use finufft alone in python, but when I use it in conjunction with cython, I receive nan values in what otherwise would be the correct output. This has happened in two cases:

1. Wrapping some other c++ code in Cython, but using the python wrapper for finufft:
```
import package-wrapped-with-cython
import finufft
```

2. Linking the c++ version of finufft into the source c++ code I'm using, then wrapping the entire thing in Cython:
```
import package-wrapped-with-cython-but-uses-finufft
```

For example, calling `finufft.nufft2d1` in the first case returns a NxN matrix with specific columns (3,12,21,...; every ninth) of the output replaced by nan values (seems to be consistent with multiple attempts) regardless of whether the imported cython package is actually used (this occurs as long as the cython package is imported). The values that are not nan appear to be exactly what it would output without the import statement.

```
import numpy as np
import finufft
import package-wrapped-with-cython

M = 100
N = 41

points = np.random.random(2*M).reshape(-1,2)
points -= np.round(points)
points *= 2*np.pi
x = points[:,0]
y = points[:,1]
c = np.ones(M) + 0j
assert x.size == y.size == c.size == M

rho = finufft.nufft2d1(x,y,c,n_modes = (N,N))
print(np.argwhere(np.isnan(rho)))
assert np.isfinite(rho).all(), 'rho is not finite'
```

The print statement gives something like:
```
[[  0   3]
 [  0  12]
 [  0  21]
 [  0  30]
 [  0  39]
 [  1   3]
 [  1  12]
 [  1  21]
 [  1  30]
 [  1  39]
 [  2   3]
 [  2  12]
 [  2  21]
 [  2  30]
 [  2  39]
...
```
And so on

**Comment by lu1and10** [comment]
To clarify,
```
import package-wrapped-with-cython
import finufft
```
outputs with NaN, and
```
import finufft
```
alone works on cython?


 To reproduce the NaN,
`import package-wrapped-with-cython` can be any package wrapped with cython, even the package only has one function wtih empty function body?

**Comment by aaron-shih** [comment]
Ah it appears it was an issue with how i had set up the environment on the computing cluster i was working on.
