### ISSUE TITLE
Possible Segfault using Python finufft package

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/finufft#215]
Hi, a user reported a crash and I traced it back to a python call into FINUFFT.  Then I reduced that down to a smaller invocation with only the `finufft` package installed in the environment.  I'm probably invoking finufft incorrectly, but I'm not sure why.  Could someone help confirm/deny it is something I've done wrong.

Thanks!

```
"""
conda create -n check_y python=3.7
conda activate check_y
pip install finufft
python check_nufft.py # this code
# segfault
"""

import numpy as np
import finufft

# Signal
print('gen large random dataset...')
X = np.random.randn(100000, 129, 129).astype(np.float32)
print('done')


# setup points
#fourier_pts = np.load('/tmp/fourier_pts.npy')  # dumped from code, but I think we can just use a linspace...
fourier_pts = np.array((np.linspace(-np.pi,np.pi, 33282),)*2, dtype=np.float32)
print(fourier_pts.shape)


# setup plan
transform_plan = finufft.Plan(nufft_type=2, n_modes_or_dim=X.shape[1:], eps=1e-8, n_trans=X.shape[0], dtype=X.dtype)
transform_plan.setpts(*fourier_pts)

# complex input array
signal = np.array(X, copy=False, dtype=np.complex64, order="C")

# transform
result = transform_plan.execute(signal)

**Comment by garrettwrong** [comment]
Hey, I think the original report was for 100k, my bad. Same problem otherwise. I'll update my code above. Thanks

**Comment by lu1and10** [comment]
You are right, for 100k*129*129 I got a segfault. For 10k*129*129 it was
fine. Not sure where it segfault, I need to debug more.

**Comment by garrettwrong** [comment]
Fwiw gdb landed me in `interpSorted`, and a bt is in the linked issue above.  Thank you Libin, and let me know if I can help.

**Comment by lu1and10** [comment]
> Fwiw gdb landed me in `interpSorted`, and a bt is in the linked issue above. Thank you Libin, and let me know if I can help.

It seems that this is a memory management problem. In the following line, numpy.zeros does not allocate all of its memory on creation.
[https://github.com/flatironinstitute/finufft/blob/master/python/finufft/_interfaces.py#L272-L273](https://github.com/flatironinstitute/finufft/blob/master/python/finufft/_interfaces.py#L272-L273)

When C++ side writing out to the result in the following lines, the memory grows(you can use top to see the memory grows to limit when running the 100K*129*129 example).
[https://github.com/flatironinstitute/finufft/blob/master/src/spreadinterp.cpp#L535-L536](https://github.com/flatironinstitute/finufft/blob/master/src/spreadinterp.cpp#L535-L536)

While even if one does allocate all memory on python side, on C++ side it may access the invalid memory space if it exceeds some limit(it seems python can access much larger virtual memory than C++ side can?).

I would say the user should either run the code on  larger memory machine, or divide the ntrans to chunks and call plan.execute multiple times to use leave memory footprint.

**Comment by garrettwrong** [comment]
Hrmm, Linux allocs have a similar sounding (on touch) behavior iirc.

This machine has over 1TB of RAM....

True, a large problem but it is consistent with reasonable use case. Let's try to make it work.

Can you use np.empty then np.fill(0) ? or since other equivalent?  I think if the problem is what you describe is the issue that would do it....

**Comment by lu1and10** [comment]
> Hrmm, Linux allocs have a similar sounding (on touch) behavior iirc.
> 
> This machine has over 1TB of RAM....
> 
> True, a large problem but it is consistent with reasonable use case. Let's try to make it work.
> 
> Can you use np.empty then np.fill(0) ? or some other equivalent? I think if the problem is what you describe as the issue that would do it....

If it's a 1TB RAM, it should work with current interface. Maybe there is something wrong, need to investigate more.
