### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#223]
Currently, support varies in terms of binary wheels across the platforms:
– For Windows, we have Python 3.8, 3.9, and 3.10
– For macOS, we have Python 3.6, 3.7, 3.8, 3.9, and 3.10
– For Linux, we also have Python 3.6, 3.7, 3.8, 3.9, and 3.10 but in addition also PyPy binaries for 3.7 and 3.8

It would be good to harmonize these versions (and list them with badges in the readme) between platforms. 3.6 is EOL as of 2021-12-23, so we can drop that one, but 3.7 is still around, so we could consider adding it to the Windows wheels. We should also think about whether we want to distribute PyPy binaries for the same versions as for CPython.

**Comment by janden** [comment]
Would be good to sort this out before the next release. @lu1and10 Do you know what the status is here?

**Comment by lu1and10** [comment]
> Would be good to sort this out before the next release. @lu1and10 Do you know what the status is here?

Now the python wheels can be built for 3.8 and beyond for windows, mac and linux. 
3.7 is end of support now, I guess we can support for 3.8 and beyond. 
pypy we only built for linux 3.8 beyond.

**Comment by janden** [comment]
Sounds good. I also found out that 3.12 was just released, so I'll start looking into that.

**Comment by ahbarnett** [comment]
Libin says binary for 3.8 should work for all >3.8.
Await #429.
