### ISSUE TITLE
Possible explanation for accuracy issue mentioned in docs

### ISSUE THREAD

**Issue by mreineck** [flatironinstitute/finufft#225]
In https://finufft.readthedocs.io/en/latest/trouble.html you mention that
> On the above topic, strangely, in single-precision, requesting tolerance of 1e-7 or 1e-6 can give slightly worse accuracy than 1e-5 or 1e-4. We are looking into this.

From my own experiments with non-uniform FFTs I have a suspicion what might be happening here ...
Consider a Type 1 transform: after doing the first two steps (spreading and FFT), you have an array of complex values. Since no correction has taken place yet, the values at high frequencies are suppressed, i.e. typically somewhat smaller than the values at low frequencies. Still, since the preceding FFT has "mixed" the array elements globally, the _absolute_ error of every array element is roughly 1e-16 (or 1e-7 for single precision) times the maximum array value, independent of its own absolute value.

Then the correction function is applied, and array values at high frequencies are multiplied with larger factors than those at low frequencies, which causes their absolute error to increase. How bad this effect is depends on the dynamic range of the correction function and on the dimensionality of the transform: the higher, the worse. 

In my own code I only use combinations of oversampling factor and kernel support that result in a correction function that is at most a factor of 10 larger at the cutoff frequency than at zero frequency. This has fixed the problem for me.

**Comment by ahbarnett** [comment]
Thanks for the advice. In the paper I conclude (empirically) that there is an additional loss of eps_mach times max{N1,N2,...} which is probably what led to that comment. The paper also explains the gap between what is observed and what can be proved mathematically; the gap is quite large. This includes the correction factor of course. If you're ok w/ it, I'll close this as an issue.
