### ISSUE TITLE
Python: Potentially too strict floating precision check

### ISSUE THREAD

**Issue by danielrotter** [flatironinstitute/finufft#232]
Currently, the Python version of FINUFFT performs as far as I can tell most (if not all) floating point precision checks using the `is` operator to compare `dtype`s. For example (from function `_rchk` / line 321 of `_interfaces.py`):
```python
if x is not None and x.dtype is not np.dtype('float64'):
    raise RuntimeError('FINUFFT data type must be float64 for double precision, data may have mixed precision types')
if x is not None and x.flags['C_CONTIGUOUS']:
    return x
else:
    return np.array(x, dtype=np.float64, order='C')
```
However, this comparison is more strict than checking if the given array `x` uses double precision values.

For example, if you load a data file that was exported from Matlab using
```matlab
>> a = rand(2)
>> save('test.mat', 'a')
```
into Python using SciPy
```python
>>> a = scipy.io.loadmat('test.mat')['a']
>>> a.dtype
dtype('<f8')
>>> a.dtype is np.dtype('float64')
False
```
the data type of the loaded array `a` will report as `dtype('<f8')` but it wont compare identical to `dtype('float64')` (even though those types should in theory be identical). The only difference between the `dtype`s seems to be their byte order and consequently the `isbuiltin` flag. Therefore, when trying to call FINUFFT with such an array you will usually get the runtime error shown above which indicates that the "data may have mixed precision types". This is because the comparison `a.dtype is np.dtype('float64')` fails even though `a` conatins double precision values.

I suppose there are other ways than importing from a Matlab data file to get the same behavior, but I have not yet encountered them...

Considering the specific function `_rchk` for input checking above, a copy of the given array will be created if the first check passes and the array is not C contiguous. In my opinion this function as well as the other functions for input/output checking should be more restrained when it comes to producing an error and instead try to create a copy of the given array in more cases...
However, this might be intended behavior to reduce the number of array copies of which a user is not aware. If that is the case, feel free to close this issue. Otherwise, from my limited experiments with `dtype`s I would suggest using one of the following comparisons as initial type checks:
```python
>>> a.dtype.kind == 'f' and a.dtype.itemsize == 8
True
```
*OR* (note: `==` instead of `is`)
```python
>>> a.dtype == np.dtype('float64')
True
```

After this initial check the given array could be either directly used if an additional type comparison using `is` passes and the data is C contiguous *OR* a copy could be created if either of those two additional checks fails.

Thanks for reading, please let me know your thoughts on this!

**Comment by ahbarnett** [comment]
Hi Daniel,
Thanks for the thoughtful suggestions and the demo of failure.

Our use of `is` instead of `==` came out of the following recent discussion, which it would be great if you could glance over:
https://github.com/flatironinstitute/finufft/issues/192
As you can see, `==` caused other problems.

I like your proposed use of
`a.dtype.kind == 'f' and a.dtype.itemsize == 8`
as a criteria to avoid error,
then have a 2nd check using `is`.

I am not a python expert, and have asked our python experts to help implement the above. Thanks, Alex

**Comment by dbstein** [comment]
The proposed solution of  `a.dtype.kind == 'f' and a.dtype.itemsize == 8` doesn't work because of the possibility of big-endian data.  I don't think there's anything that can go wrong with `a.dtype == np.dtype('float64')`, though.  Try the below:

```python
np.dtype('<f8') == np.float64 # returns True
```

**Comment by dbstein** [comment]
> You are implying that big-endian data is not supported by FINUFFT when it comes to the internal C++ implementation, correct?

Python is just handing a pointer to FINUFFT and the data that FINUFFT sees at that location will be interpreted as the native float (or double) type (which on an x86 processor is little-endian).  Our job is just to make sure that pile of data sitting there should be interpreted in that manner.  If both python and FINUFFT were built instead on an old IBM mainframe, FINUFFT would interpret the data there as big-endian floats and np.float64 would also be a big-endian type. From a python/FINUFFT interop point of view, x.dtype == np.dtype('float64') is the correct thing to do, as it ensures that x has native 8 byte floats. On modern hardware (x86) Numpy correctly aliases '<f8' to 'float64', so in your case all would be fine. I think this confusion is unlikely to happen, the example is mainly to point out how moving to painful lower level tests, such as `a.dtype.kind == 'f' and a.dtype.itemsize == 8`, can be fraught with error. A line like `x.astype('<f8', order='C', casting='equiv', copy=False)` in the _rchk function is similarly fraught with error, as it makes unnecessary assumptions about the hardware the code is running on. 

The only real issue with endianness is with data read in from a file. It's perfectly conceivable that someone loads up some legacy data (produced on different hardware) which is in big-endian. Of course, that isn't FINUFFT's problem, and we'd be right to just throw an error. It's the responsibility of the user to ensure the data they load is converted to native format before passing it to low level functions.

The simplest solution to this issue really is just to change `is` to `==` in the type-checking, but I think something like:

```python
FINUFFT_INPUT_RQMTS = ['C', 'A']
FINUFFT_OUTPUT_RQMTS = ['C', 'A', 'W']

def _chk(x, variable_name, precision, output):
    """
    Check if array x is of the appropriate type / satisfies flags
    Precision checking is strict and will throw an error
    The array x should also satisfy FINUFFT_*_RQMTS (* for INPUT/OUTPUT)
    For inputs these are not strictly enforced but cause copies; and a
        performance warning is issued to the user
    For ouptuts, these are strictly enforced and result in an error.
        If the user cannot be sure they're handing proper output data
        into the function, they should let the function allocate the output
    """
    if x is None: # this just allocates a small dummy array
        return np.array(0, dtype=precision.p, order='C')
    if x.dtype != precision:
        raise RuntimeError(_generate_typing_error(x, variable_name, precision))
    rq = FINUFFT_OUTPUT_RQMTS if output else FINUFFT_INPUT_RQMTS
    out = np.require(x, dtype=precision, requirements=rq)
    if x is not out:
        _rq_warn_or_error(x, variable_name, rq, output)
    return out
```
is a better way to go, throwing more of the testing requirements back to numpy (which can enforce alignment and writeability, too).  I've written a few extra functions to produce better error messages, like:
```python
RuntimeError: Typing requirements are strict. The varaible a has type complex128; the required type was float64.
```
```python
RuntimeError: 
Given output variable a does not satisfy all requriments. These are:
['C', 'A', 'W']
The flags associated with the array a are
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```
but don't really have time to do full tests right now.

**Comment by matthieumeo** [comment]
Hi there, I just wanted to mention that I also encountered this issue when working with the output of Dask array computations: somehow the dtype was changed by Dask in a very subtile manner so that the ``is`` test would not pass anymore but the ``==`` one would. I think that going for the ``==`` test is indeed the way forward here.

**Comment by danielrotter** [comment]
> will be interpreted as the native float (or double) type

Yes of course that makes more sense. I was just confused as you explicitly stated that a low-level comparison would cause a problem with big-endian data.

> A line like `x.astype('<f8', order='C', casting='equiv', copy=False)` in the _rchk function is similarly fraught with error, as it makes unnecessary assumptions about the hardware the code is running on.

Well for me the type `'=f8'` instead of `'<f8'` seems to do the correct thing on my little-endian CPU with given arrays of any endianness. Assuming the implementation in NumPy is consistent it should most likely also work the other way around. I did notice however that you have to set `copy=True`, if you want to "reset" the associated flags for data which already has the correct endianness. So after `x.astype('=f8', order='C', casting='equiv', copy=True)` the original check with `x.dtype is np.dtype('float64')` should always be satisfied. Alternatively, after `x.astype('=f8', [...], copy=False)` the `byteorder` might not be set to `'='` (but instead to the explicit native byte-order) which would not satisfy the original condition, but should still yield correct data for the underlying low-level implementation (i.e. satisfy `x.dtype == np.dtype('float64')`).

I do not know if there would be a meaningful difference (other than the "strictness" perceived by a user) between `x.astype('=f8', [...])` and the comparison `x.dtype == np.dtype('float64')` followed by an exception. It seems to me they accomplish the same task. In the end it is of course up to you to decide whether the user interface should be "stricter" or more "forgiving"...
