### ISSUE TITLE
cmake test should diff check the terminal outputs for testutils/dumbinputs

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#253]
We need to add to the CMake / ctest a step that diffs the *.out against the *.refout
Grep for `diff` in my old `test/check_finufft.sh`

Currently the ctest merely runs testutils, dumbinputs{f}   but does nothing to check their output, which is their point.

Tweaks to add diffs to these ctest commands would be needed:
https://github.com/flatironinstitute/finufft/blob/a0db2d0b2ce275f450095a1007208d21a52a9be9/test/CMakeLists.txt#L25
https://github.com/flatironinstitute/finufft/blob/a0db2d0b2ce275f450095a1007208d21a52a9be9/test/CMakeLists.txt#L53

This is important for long-term CI since it tests various edge cases.

The question is if `diff` is available on windows - @DiamonDinoia Marco or @lu1and10 maybe you know this?

**Comment by DiamonDinoia** [comment]
Diff is not available on windows there's FC: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fc

diff is available on cygwin if that can be installed on a github action

**Comment by ahbarnett** [comment]
@lu1and10 What do you think a solution is here for testutils and dumbinputs{f} ? (Since I don't know much about CI).  DOes the lack of diff issue force us to make executables that return exit code, like I did with the finufft?d*_test{f} executables?
Or is there a neater way to do it, or to install diff in the CI setup?
Maybe we can chat tomorrow? Thanks, Alex

**Comment by lu1and10** [comment]
> @lu1and10 What do you think a solution is here for testutils and dumbinputs{f} ? (Since I don't know much about CI). DOes the lack of diff issue force us to make executables that return exit code, like I did with the finufft?d*_test{f} executables? Or is there a neater way to do it, or to install diff in the CI setup? Maybe we can chat tomorrow? Thanks, Alex

@ahbarnett I think command `cmake -E compare_files file1 file2`  can compare two files, if same exit code should be 0, otherwise 1.
Yes, we can chat today, met with Joakim yesterday, but haven't started chat about cufinufft with him and Robert yet.
