### ISSUE TITLE
In Windows 10，I use cmake to build the project，there have an error

### ISSUE THREAD

**Issue by OneMuMuYan** [flatironinstitute/finufft#260]
Detecting CUDA compiler ABI info - done
Check for working CUDA compiler: C:/Software/CUDA11.6/NVIDIA_CUDA_Development/bin/nvcc.exe - skipped
Detecting CUDA compile features
Detecting CUDA compile features - done
Configuring done
CMake Error at src/cuda/CMakeLists.txt:54 (add_library):
  Target "cufinufft_static" links to target "CUDA::cufft_static" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/cuda/CMakeLists.txt:54 (add_library):
  Target "cufinufft_static" links to target "CUDA::cufft_static" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by DiamonDinoia** [comment]
CUDA::cufft_static does not exist on windows, we would need to change the cmakefile with an if(WIN32) and use CUDA::cufft on Windows
