### ISSUE TITLE
Move compilation out of cufinufft dockerfile

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#305]
Compile as part of Jenkins/wheel-building instead (see https://github.com/flatironinstitute/finufft/pull/300#issuecomment-1611842773).

**Comment by janden** [comment]
@blackwer Newbie Docker question: How do I replicate what Jenkins is doing when it's executing the various steps in the CI pipeline? When I run `docker run`, any changes made don't seem to persist in the container. Is the trick here to create a container and keep referring to it by name in any invocations of `docker run` or should I do something else here?

I'm asking because we use the same Dockerfile for creating the binary wheels and it's currently a two-step process (`docker build` followed by `docker run`). But now I want to move the library building out into a separate file, which would require two instances of `docker run` (I guess I could merge them into one call, but it would be nice to know how this works more generally).

**Comment by janden** [comment]
Nm I think I got it. It's `docker exec`, right?

**Comment by blackwer** [comment]
I always just open up a shell inside the docker container and do my thing. If I'm building a pipeline, I'll copy my history out and paste the command sequence into the dockerfile basically. In short, I'm no help here. I hate containers :)

**Comment by janden** [comment]
Got it. Think I figured it out….

**Comment by janden** [comment]
Closed by #320.
