### ISSUE TITLE
Can this library be applied to PyTorch?

### ISSUE THREAD

**Issue by lalalashini** [flatironinstitute/finufft#307]

**Comment by janden** [comment]
There is also an effort by @eickenberg and others to do this along with cufinufft integration.

**Comment by blackwer** [comment]
In addition to the wrappers being developed above, which should be used for now, we'll hopefully be adding support for other cuda capable libraries in the next major release. See: https://github.com/flatironinstitute/finufft/pull/326

**Comment by janden** [comment]
Closing this for now.
