### ISSUE TITLE
Docs for Python interface : "Full Documentation" H2 empty

### ISSUE THREAD

**Issue by mjachi** [flatironinstitute/finufft#328]
I'm expecting this was unintentional and it seems to have not been pointed out yet -- currently, the "Full Documentation" section detailing the Python API simple and full interfaces is empty. See [here](https://finufft.readthedocs.io/en/latest/python.html).

**Comment by mjachi** [comment]
The two most recent snapshots on the Wayback Machine are 9/30/2022, which has it, and 6/3/2023, which {is currently erroring so I cannot check for certain}

**Comment by janden** [comment]
Thanks for catching this. Looks like we forgot to update the Sphinx config with the new directory structure. Should be fixed by #329.
