### ISSUE TITLE
update docs re local python build

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#340]
This goes naturally with https://github.com/flatironinstitute/finufft/pull/238 :

docs/install.rst seciton on how to local py build should be updated to Joakim's procedure, as we obsolete the makefile:

              1. So the way I compiled and installed was the following
```
make -p build
cd build
cmake ..
make -j
cd ..
pip install -e python/finufft
```

Then I run `pytest python/finufft/test` and everything passes. From what I understand, `make python` essentially does this last line (`pip install -e python/finufft`), so that makes sense.

We should first describe the new "download from pypi" version:

In a fresh venv, I just ran

```
pip install finufft
pytest python/finufft/test
```

Thanks! Alex

_Originally posted by @janden in https://github.com/flatironinstitute/finufft/issues/238#issuecomment-1701605776_

**Comment by ahbarnett** [comment]
Hi Joakim, Since you've now updated the py build and test, the docs have drifted out of date. Could you replace them with your procedure ... if it's the one users should use?
There's a minor decision:
Do we want to explain how to run the old accuracy/speed tests before we force them to install pytest?
Thanks,  Alex

**Comment by janden** [comment]
> Hi Joakim, Since you've now updated the py build and test, the docs have drifted out of date. Could you replace them with your procedure ... if it's the one users should use?

Sounds good. I'll take a look.

> Do we want to explain how to run the old accuracy/speed tests before we force them to install pytest?

Yeah I don't see why not. Will make a PR.

**Comment by ahbarnett** [comment]
I'm actually confused how ``pip install -e python/finufft`` can possibly know to look in ``build`` when the CMake library build is used (which doesn't write anything to ``FINUFFT/lib/``) According to ``setup.py`` it doesn't look there. Are you sure your above instructions weren't relying on a binary NOT built by cmake ?   I will add it to the PR I'm doing for this Issue.

**Comment by ahbarnett** [comment]
According to
https://setuptools.pypa.io/en/latest/userguide/ext_modules.html
the `libraries` tag should not have the path in it. This would allow multiple paths to be searched, eg to allow either CMake (build/) or makefile (lib/) locations.
