### ISSUE TITLE
Handle actual cuda errors gracefully

### ISSUE THREAD

**Issue by blackwer** [flatironinstitute/finufft#347]
Currently most cuda errors are handled via the helper macro `checkCudaErrors` which calls `exit(1)`. This is almost certainly not the behavior most people want, as the library will exit their calling program -- even if it's some interactive environment like matlab, jupyter, python, etc.

**Comment by ImanHosseini** [comment]
Some thoughts on error handling:
1. Error handling is super useful. When something fails I want to know exactly which cuda call failed.
2. Error handling is not free. When everything works, I don't want to pay the overhead for checking it. 
So one solution that can satisfy both would be:
```
inline void __checkCudaErrors(cudaError_t err, const char *file, const int line)
    {
        const char *ename;
        const char *estr;
        ename = cudaGetErrorName(err);
        estr = cudaGetErrorString(err);
        if (cudaSuccess != err)
        {
            fprintf(stderr,
                    "CUDA Runtime API error = %04d from file <%s>, line %i:\n",
                    err, file, line);
            fprintf(stderr, "\t%s : %s\n", ename, estr);
            exit(-1);
        }
    } 
#ifdef DBG
#define ccE(err) __checkCudaErrors(err, __FILE__, __LINE__)
#else
#define ccE(err) err
#endif
```
And then wrapping every cuda call with ccE, i.e. ccE(cudaMalloc(...)). Not only does it print exactly what the error was, it would also show file and line number. _and_ it can be turned off/on at compilation, so if I am not investigating a crash, there is 0 overhead. If there's a crash, then I can use the debug build. 
Thoughts?
