### ISSUE TITLE
Windows mex binary doesn't work for Windows 11, Matlab 2023a

### ISSUE THREAD

**Issue by Divisible8737** [flatironinstitute/finufft#351]
I'm on Windows 11 Enterprise, 64-bit operating system, x64-based processor, using Matlab 2023a.

I downloaded the stable release https://github.com/flatironinstitute/finufft/releases/tag/v2.0.2, then placed it here 'C:\finufft-2.0.2.'  I then downloaded the mex file `finufft.mexw64` from https://users.flatironinstitute.org/~ahb/codes/finufft-binaries/2.0.2/ and placed it in the folder 'C:\finufft-2.0.2\matlab'.  The entire `'C:\finufft-2.0.2` is in my path. Now, with calls to FINUFFT functions in the check_finufft script, I get  the following error
```matlab
Invalid MEX-file 'C:\finufft-2.0.2\matlab\finufft.mexw64': The specified module could not be found.
``` 

There appear to be [several possible causes](https://www.mathworks.com/matlabcentral/answers/92040-why-do-i-receive-a-specified-module-could-not-be-found-error-while-running-a-mex-file-in-matlab), like wrong Matlab version, missing libraries, etc.  Is there a recommended version of Matlab and are there any other things I can try to get the FINUFFT working on Windows?

Thanks

**Comment by lu1and10** [comment]
There is a new matlab windows mex binary in the following link, could you try that?

[https://drive.google.com/drive/folders/1OMiM5BKSvX0As7udx0PEmR5dEWYiNcK3?usp=drive_link](https://drive.google.com/drive/folders/1OMiM5BKSvX0As7udx0PEmR5dEWYiNcK3?usp=drive_link)

**Comment by Divisible8737** [comment]
@lu1and10, THANK YOU!!! Your compiled binary works with the latest clone of master.

**Comment by ahbarnett** [comment]
closing, but Libin we should gather your binaries into release assets
