### ISSUE TITLE
Python: Consider raising ImportError when shared libraries not found

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/finufft#379]
Currently a `RuntimeError` is raised. By convention, this is a catch-all error:

> Raised when an error is detected that doesn’t fall in any of the other categories. The associated value is a string indicating what precisely went wrong.

By contrast, the description for `ImportError`:

> Raised when the [import](https://docs.python.org/3/reference/simple_stmts.html#import) statement has troubles trying to load a module. Also raised when the “from list” in from ... import has a name that cannot be found.

So if the user types `import finufft` or `import cufinufft`, it seems reasonable to expect an ImportError rather than a RuntimeError

**Comment by lu1and10** [comment]
Thanks, never thought about error types.
So is the solution to replace `RuntimeError` with `ImportError` in the following lines or there is other standard?
[https://github.com/flatironinstitute/finufft/blob/98ab7e457c85468090480a64de47372b5d1e5cf7/python/cufinufft/cufinufft/_cufinufft.py#L55](https://github.com/flatironinstitute/finufft/blob/98ab7e457c85468090480a64de47372b5d1e5cf7/python/cufinufft/cufinufft/_cufinufft.py#L55)
[https://github.com/flatironinstitute/finufft/blob/98ab7e457c85468090480a64de47372b5d1e5cf7/python/finufft/finufft/_finufft.py#L64](https://github.com/flatironinstitute/finufft/blob/98ab7e457c85468090480a64de47372b5d1e5cf7/python/finufft/finufft/_finufft.py#L64)

**Comment by WardBrian** [comment]
That should be all, yes!

**Comment by lu1and10** [comment]
> That should be all, yes!

Thanks! Just changed in commit 193b1d6c7358a4847411a6ebac258cfc09026060
