### ISSUE TITLE
What is `lgwt` and where can I find it?

### ISSUE THREAD

**Issue by tomsturges** [flatironinstitute/finufft#381]
Hello,

In [this documentation page](https://finufft.readthedocs.io/en/latest/tutorial/contft.html) about evaluating continous Fourier transforms, a function called `lgwt` is used. However I can't find this function within the python interface of finufft. What is this function and where can I find it?

Thanks!
Tom

**Comment by lu1and10** [comment]
Hi,

It’s in the tutorial fold, it’s a quadrature for continuous function. I guess the part of tutorial code is written in matlab.

https://github.com/flatironinstitute/finufft/blob/master/tutorial/utils/lgwt.m

**Comment by tomsturges** [comment]
Ah ok thank you
