### ISSUE TITLE
Pip link static library into cython object

### ISSUE THREAD

**Issue by blackwer** [flatironinstitute/finufft#389]
Currently we RPATH in the shared library

**Comment by blackwer** [comment]
@DiamonDinoia @janden 
OK I looked into this for `cufinufft` and I'm not convinced it's a great idea. 
1. at least naively, as as I understand the problem now, `gcc` doesn't know how to relocate the symbols from the static library into a shared one, so you get "can't find `cudaRegisterLinkedBinary_XXXXX` blahblah" symbol errors.
2. You probably have a relatively simple solution to this, @DiamonDinoia, but the symbols aren't trivially injected with `gcc` in the first place, because by default it only links reachable symbols. The `export_symbols` option does not seem to help here, so we'd basically need to make a stub file with the public API so everything is reachable. I did a trick like this `extra_link_args=['-Wl,--whole-archive', extra_objects[0], '-Wl,--no-whole-archive', '-lstdc++'],` but that's how I found out about issue 1 above.

This seems like it's going to be even messier than just injecting the `RPATH` into the library as we do now.

**Comment by DiamonDinoia** [comment]
Hi @blackwer,

Just to check. Are we using -fpic when building? 
I only encountered this error in cmake and the fix was `set_target_properties(hello PROPERTIES LINKER_LANGUAGE CUDA)`. No idea how to achieve that in make/setup.py.

**Comment by blackwer** [comment]
> Just to check. Are we using -fpic when building?

yeah everything is `fpic`. This all seems very overly complicated. I'm fully advocating now that we just copy the shared library in with the python files and call it a day. Gets rid of all this 'find my library' boilerplate code (mostly). Should have less problems on windows in general. Removes the necessity of a compiler/linker being available at pip install time (I just had an issue where `pip install` was using a different `gcc` than the module I had and wouldn't work). Should make the `pyproject.toml` conversion simpler too.
