### ISSUE TITLE
Wheels for apple silicon

### ISSUE THREAD

**Issue by blackwer** [flatironinstitute/finufft#404]
Right now we improperly tag our wheels as universal, but they don't work on apple silicon. I think, after #403 is merged, we should work on sorting this out (post 2.2 release). We should be able to build them using the current github runners, though not test. See:
https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

In short, everything needs to be built with the `-arch arm64` flag using apple's clang. I'm not sure if we should bother with `gcc` here.

If we wanted to test without shelling out to github, we can build and test on the flatiron jenkins resources, which has an M1 around. I'm not sure if this is worth it, given we've never had an apple silicon user complain that finufft doesn't work.

**Comment by janden** [comment]
ASPIRE has some users for which arm is relevant: https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/962 and https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/968. Those were related to PyFFTW, though, not finufft, although I suspect this may have been masked by the PyFFTW incompatbility.

**Comment by janden** [comment]
Solved by de9e9a6 (I think).

**Comment by ahbarnett** [comment]
Libin solved it, closing.
