### ISSUE TITLE
Not resetting number of threads

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#42]
When calling a FINUFFT function with a specified number of threads, i.e., `opts.nthreads = 1`, subsequent OpenMP code will use the same number of threads. In other words `omp_get_num_threads()` might return `8` prior to a FINUFFT call, while after, it may give `1`.

It might not be a good for FINUFFT to change the global state in this way, since the caller may not realize that they are permanently changing the number of OpenMP threads whenever they call FINUFFT with a specified number of threads.

**Comment by ahbarnett** [comment]
this has to be matlab interface, right? (the library itself never sets omp numthreads)
Omp seems to have an internal state that it changes, which is inaccessible from matlab (eg maxNumCompThreads can't see it).
I will store the state and restore, see if that workds...   A

**Comment by janden** [comment]
Looks like it. `finufft_mex_opts` seems to be where it's set. Are the other interfaces doing the same thing?
