### ISSUE TITLE
Linking order in makefile

### ISSUE THREAD

**Issue by vineetbansal** [flatironinstitute/finufft#46]
While building finufft under Windows/MinGW, I had to move the -l flags in the makefile towards the end of the command line in question. For example:

```
$(DYNAMICLIB): $(OBJS) $(HEADERS)
	$(CXX) -shared $(OMPFLAGS) $(LIBSFFT) $(OBJS) -o $(DYNAMICLIB)
```
had to be changed to:
```
$(DYNAMICLIB): $(OBJS) $(HEADERS)
	$(CXX) -shared $(OMPFLAGS) $(OBJS) -o $(DYNAMICLIB) $(LIBSFFT) 
```

Looks like this is a GNU requirement, though MinGW enforces it strictly. See the last paragraph at http://www.mingw.org/wiki/specify_the_libraries_for_the_linker_to_use

**Comment by ahbarnett** [comment]
Dear Vineet - 
Thanks -done. My bad. Linux & mac didn't care.
But this is exciting that it works on Windows. Would you care to provide any instructions I could add to:
docs/install.rst ?
Best, Alex

**Comment by vineetbansal** [comment]
Sure..I'm trying to figure out which tweaks I performed are specific to my Windows fftw installation vs. what would apply in general. Also there are many ways to get things working - msys vs. mingw vs. installing the m264-toolchain in conda etc., so I'm still trying to come up with a path of least resistance for Windows users :)

**Comment by ahbarnett** [comment]
At your leisure...  (we don't use windows).
But I often find that making my own install docs is my way to document even just for my own later sanity :)  Say hi to Amit. Best, Alex
