### ISSUE TITLE
finufft2d1many and 2d2many fftw plan many falls off end of data array

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#50]
If eg ndata < nth, the following plans an fftw that acts on data outside the end of the user's stacked strength arrays...

  FFTW_PLAN p = FFTW_PLAN_MANY_DFT(2, n, nth, fw, n, 1, n[0]*n[1], fw, n, 1,
                                   n[0]*n[1], fftsign, opts.fftw);

Melody, we need to check this doesn't segfault, etc..

**Comment by MelodyShih** [comment]
Hi Dr. Barnett, 

In the code we always allocated `nth*nf1*nf2` amount of data for `fw` array even when ndata<nth. I think that prevents fftw from accessing an invalid data?
 
Best, 
Melody

**Comment by ahbarnett** [comment]
Yes, you're right. It works. But there is a potential for over-allocation, eg if arrays are big and ndata << nth.
Andrea is writing a CPU guru interface similar to your GPU one, so we could combine them later.
This will replace the basic and "many" interfaces.
