### ISSUE TITLE
require fftw 3.3.9 and use planner_nthreads in finufft.cpp

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#521]
https://github.com/flatironinstitute/finufft/blob/cdcccbec2585ae2ab5bf2e0be27bac1c526fa6c3/src/finufft.cpp#L764

rewrite that fftw plan call using fftw_planner_nthreads.
See https://www.fftw.org/release-notes.html
3.3.9 was released Dec 2020.

Julia crash may be related to this:
https://github.com/ludvigak/FINUFFT.jl/issues/61

**Comment by jkrimmer** [comment]
Hi Alex,

I have implemented a first draft to use fftw_planner_nthreads at #526. Based on this PR, I have built the finufft library for julia on Windows. Although, the library seems to work fine, the issue described in `https://github.com/ludvigak/FINUFFT.jl/issues/61` persists.

Cheers
Jonas

**Comment by DiamonDinoia** [comment]
It seems more of a FFTW.jl issue https://github.com/JuliaMath/FFTW.jl/issues/306. Shall we delay this to 2.4.0 or 2.3.1, in case we do a bugfix release? More investigation is needed in any case.

**Comment by ahbarnett** [comment]
Robert has created a longer-term solution in the form of a user lock (adding 3 opts fields):
https://github.com/blackwer/finufft/tree/user_fftw_lock

Propose we assess that for 2.4 and extend it to language wrappers.

**Comment by ahbarnett** [comment]
closing since we're pretty much stuck with FFTW 3.3.8.
