### ISSUE TITLE
perftest: diagnose delays in v2.2.0 multithreaded; diagnose fftw makeplan

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#553]
These are two things to tidy up with the performance bench.py and perftest.cpp.
They don't have to be done before 2.3.0 tag, but 1st should be done before we announce, so we trust the speedups.

**Comment by DiamonDinoia** [comment]
It should be fixed in master now.

**Comment by ahbarnett** [comment]
Thanks. I just pulled master and speedups make more sense, and look stable. It is typically factor 1.5 speedup due to manual SIMD. However, don't you think it's weird that DUCC and FFTW are essentially identical? I think this is because the spreadinterp takes >90% of the time. The FFTs take <5% of the time in most examples, so we don't get to showcase the faster DUCC in 2d and 3d.  Consider changing one of the cases to smaller M, larger N1,N2,N3, to showcase FFT speedups...

**Comment by DiamonDinoia** [comment]
I think this is done in #527
