### ISSUE TITLE
Mac wheel builds broken

### ISSUE THREAD

**Issue by blackwer** [flatironinstitute/finufft#563]
https://github.com/flatironinstitute/finufft/actions/runs/10910960544/job/30286067165?pr=548

Some issue with brew and parsing the output. Is there not a more stable way to get available packages via the cli?

**Comment by lu1and10** [comment]
It might be fixed in commit 1842601920407730463bbdfe42c5b9a21f4b4dd6, the grep was getting both *.json and *.tar.gz files, the *.json was auto removed after downloading resulting in the file not found.
