### ISSUE TITLE
change opts.gpu_spreadinterponly to opts.spreadinterponly  so fwd-compat with a CPU such use-case

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#572]
to do before 2.4

- [ ] add opt to finufft.fh       <- was meaningless since not  finufft_opts we're proposing to change!  Was cufinufft_opts.

**Comment by ahbarnett** [comment]
@chaithyagr We were wondering if you need this opt on CPU too? If so, we should change its name and implement smae logic for CPU.... (before 2.4 release, so we don't have to change the opt name later...)   what do you think?

**Comment by chaithyagr** [comment]
I agree with you, while i can do it, I'm afraid I'm not free at the moment to handle it immediately.

**Comment by ahbarnett** [comment]
Would it be fine with you if we change the name of the opt while it's easy to do so :) ?

**Comment by fzimmermann89** [comment]
We would be interested in getting this option on CPU as well  -  for density compensation in mri.

Also, this could be used in conjunction with torch's ftt, avoiding fft planning and obeying pytorchs multi threading settings.

Is this planned @ahbarnett ?
