### ISSUE TITLE
gcc bottle tag arm64_monterey on latest brew

### ISSUE THREAD

**Issue by lu1and10** [flatironinstitute/finufft#590]
The latest version brew seems to remove the gcc bottle of tag `arm64_monterey`
`brew fetch --force --bottle-tag=arm64_monterey gcc` gives `Warning: Bottle for tag :arm64_monterey is unavailable.` with the latest version brew causing the CI breaks.
https://github.com/flatironinstitute/finufft/blob/33d80c3ee39f5d2a801914fe8d5068d1aa5298ad/.github/workflows/python_build_wheels.yml#L59

@janden while `brew fetch --force --bottle-tag=arm64_ventura gcc` still works, but it's OSX 13, should we update the python wheels to MACOSX_DEPLOYMENT_TARGET=13 from MACOSX_DEPLOYMENT_TARGET=12?

**Comment by lu1and10** [comment]
Since macOS 12 (Monterey) is [unmaintained](https://endoflife.date/macos) and brew removed the gcc@14 bottle for macOS 12 (Monterey) https://github.com/Homebrew/homebrew-core/commit/b29e1a72be0ae73c92955cb445d4e879fe2fff14.
Update the python wheel ci with MACOSX_DEPLOYMENT_TARGET=13 in commit 4d25c21b9f5085c839d724b249f02fcb806158a3

**Comment by janden** [comment]
Sorry I missed this. Looks fine to me. Thanks for putting in the fix!
