### ISSUE TITLE
Fortran finufft_opts type alignment with  C struct in finufft_opts.h

### ISSUE THREAD

**Issue by alwhite-LANL** [flatironinstitute/finufft#593]
c     Fortran header recreating finufft_opts struct in fortran (f90 style).
c     This must be kept synchronized with finufft_opts.h, matching its order.
c     Also see ../fortran/finufftfort.cpp.  Barnett 5/29/20. One prec 7/2/20.

In the main branch the fortran module (finufft_mod.f90) and header files (finufft.fh) finufft_opts types ordering does not match with the C struct (finufft_opts.h). This breaks changing options with Fortran.

**Comment by ahbarnett** [comment]
Dear Al, Thanks for catching this! This code drift illustrates our lack of CI in fortran (fixing the fortran examples to prevent a crash did not actually check that, for instance, upsampfac was correctly passed in). Please pull master and it should be ok now.
