### ISSUE TITLE
slows down when given large number (>16) of threads

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#62]
This is a report from Amit Halevi at Princeton, that FINUFFT (I think for 3D type 1) slows down a lot when given a large number of threads on a big machine, eg 48 cores, 96 threads, becomes several times *slower* than 12 or 16 threads on that same machine.  Ie the parallel scaling bottoms out badly. This is a RAM access limitation, maybe due to NUMA? This needs to be verified, fixed, or at least prevented by fixing a max omp numthreads in the code.

**Comment by ludvigak** [comment]
Do you know if that is independent of problem size, or is 48 cores worse than 16 even for very large problems? Otherwise it could be that the subproblems assigned to the threads are just too small, in which case we could do some heuristics to determine a threads limit based on the problem size.

**Comment by janden** [comment]
> Do you know if that is independent of problem size, or is 48 cores worse than 16 even for very large problems?

IIRC, yes. We deal with NUFFTs often running tens of minutes and reducing to 16 threads gives us a good speedup there.

**Comment by ludvigak** [comment]
I have access to a machine where I could try this out. Could you give me a rough indication of the problem dimensions where this happens?

**Comment by janden** [comment]
Trying to reproduce it now. Ran into this a while back, so I don't have everything right in front of me.

**Comment by ahbarnett** [comment]
Since v2.0.0 this has been addressed by MAX_USEFUL_NTHREADS in include/defs.h
See logic in src/finufft.cpp.
The user can override via opts.nthreads.

**Comment by ahbarnett** [comment]
My tests on time spent waiting in ``omp critical`` for dir=1 are in issue #160.
This suggests why going beyond 24 threads is bad - the fraction of time waiting here grows in proportion to nthreads. See mutex discussion in that issue for ideas.
