### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Sketos** [flatironinstitute/finufft#68]
I am having some trouble installing finufft on macOS 10.14.6. "run test" doesn't give me any crashes but when I try to "make python" I get the following error (I tried to do "make lib" and then "make python" but the same problem occurs):

ccbh87@CISs-MBP finufft-master $ make python
pip install .
Processing /Users/ccbh87/Desktop/finufft-master
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from finufftpy==1.1.2) (1.17.2)
Requirement already satisfied: pybind11>=2.2 in /opt/anaconda3/lib/python3.7/site-packages (from finufftpy==1.1.2) (2.5.0)
Building wheels for collected packages: finufftpy
  Building wheel for finufftpy (setup.py) ... done
  Created wheel for finufftpy: filename=finufftpy-1.1.2-cp37-cp37m-macosx_10_9_x86_64.whl size=603044 sha256=c52948d3a59533b446bb50df34e9674bb9600df8801ab55040506fa611eb7e01
  Stored in directory: /Users/ccbh87/Library/Caches/pip/wheels/35/64/7b/f3c831baac2cca53d1111b005301b9224382edaaaf5049a0e9
Successfully built finufftpy
Installing collected packages: finufftpy
  Found existing installation: finufftpy 1.1.2
    Uninstalling finufftpy-1.1.2:
      Successfully uninstalled finufftpy-1.1.2
Successfully installed finufftpy-1.1.2
python python_tests/demo1d1.py
Traceback (most recent call last):
  File "python_tests/demo1d1.py", line 5, in <module>
    import finufftpy
  File "/Users/ccbh87/Desktop/finufft-master/finufftpy/__init__.py", line 23, in <module>
    from finufftpy._interfaces import nufft1d1,nufft1d2,nufft1d3,nufft2d1,nufft2d1many,nufft2d2,nufft2d2many,nufft2d3,nufft3d1,nufft3d2,nufft3d3
  File "/Users/ccbh87/Desktop/finufft-master/finufftpy/_interfaces.py", line 12, in <module>
    import finufftpy_cpp
ImportError: dlopen(/opt/anaconda3/lib/python3.7/site-packages/finufftpy_cpp.cpython-37m-darwin.so, 2): Symbol not found: ___kmpc_barrier
  Referenced from: /opt/anaconda3/lib/python3.7/site-packages/finufftpy_cpp.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda3/lib/python3.7/site-packages/finufftpy_cpp.cpython-37m-darwin.so
make: *** [python] Error 1

**Comment by lu1and10** [comment]
It seems that this is related to openmp library linking. If you are using clang on Mac, flag -lomp should be used for linking. If you are using gnu gcc on Mac, flag -lgomp should be use.
BTW what do you mean by "run test", do you mean "make test"?

**Comment by lu1and10** [comment]
Hi Amvrosiadis,

It seems that this is related to openmp library linking. If you are using
clang on Mac, flag -lomp should be used for linking. If you are using gnu
gcc on Mac, flag -lgomp should be used.
BTW what do you mean by "run test", do you mean "make test"?

**Comment by Sketos** [comment]
Thank you for your quick response. Indeed I did mean "make test" before.

Shouldn't these flags be automatically set when I execute "cp make.inc.macosx_clang make.inc" for clang on Mac? Do I need to set them somewhere manually?

**Comment by lu1and10** [comment]
"make test" works for c++ compilation, "cp make.inc.macosx_clang make.inc"
does work for c++ compilation. While for python, the link flag is set in
setup.py, you can try to modify line 49 in the setup.py to link with omp
instead of gomp.
In the future FINUFFT release, we are going to make setup.py to load the
makefile variables instead of set the flags in setup.py.

**Comment by Sketos** [comment]
Thank you very much! That seemed to have fixed the problem. I still seem to be getting one more error, which you can see below, but it seems that it is macOS related.

To fix this all I had to do is add the following line after importing finufftpy (in case other people run in to this problem)

`os.environ['KMP_DUPLICATE_LIB_OK']='True'`


**ERROR:**

make python
pip install .
Processing /Users/ccbh87/Desktop/finufft-master
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from finufftpy==1.1.2) (1.17.2)
Requirement already satisfied: pybind11>=2.2 in /opt/anaconda3/lib/python3.7/site-packages (from finufftpy==1.1.2) (2.5.0)
Building wheels for collected packages: finufftpy
  Building wheel for finufftpy (setup.py) ... done
  Created wheel for finufftpy: filename=finufftpy-1.1.2-cp37-cp37m-macosx_10_9_x86_64.whl size=603036 sha256=241b69a5b511610259de0c1b1501de7b62e0f0b7114de4b0898e0566bb6526bf
  Stored in directory: /Users/ccbh87/Library/Caches/pip/wheels/35/64/7b/f3c831baac2cca53d1111b005301b9224382edaaaf5049a0e9
Successfully built finufftpy
Installing collected packages: finufftpy
  Found existing installation: finufftpy 1.1.2
    Uninstalling finufftpy-1.1.2:
      Successfully uninstalled finufftpy-1.1.2
Successfully installed finufftpy-1.1.2
python python_tests/demo1d1.py
Finished nufft in 0.088 seconds. Checking...
Error relative to max of F: 5.79e-11
Finished nufft in 0.054 seconds (modeord=1)
Error relative to max of F: 5.79e-11
Finished nufft in 0.093 seconds (upsampfac=1.25)
Error relative to max of F: 1.03e-11
python python_tests/run_accuracy_tests.py
Accuracy and speed tests for 100000 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  9.44e-07
    CPU time (sec)  0.0235
    tot NU pts/sec  4.25e+06

finufft1d2:
    Est rel l2 err  5.8e-07
    CPU time (sec)  0.0143
    tot NU pts/sec  6.97e+06

finufft1d3:
    Est rel l2 err  3.56e-07
    CPU time (sec)  0.0124
    tot NU pts/sec  1.61e+07

OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
make: *** [python] Abort trap: 6

**Comment by lu1and10** [comment]
I think this may be because of there is an intel openmp
library(libiomp5.dylib) has been installed, and also some other openmp
lib(libomp.dylib, installed using brew openmp lib), the FINUFFT C++ static
library links with one openmp lib and the python setup.py links with intel
openmp lib. You can also change the LIBRARY_PATH to exclude intel openmp
lib path and just use one openmp lib.
btw, In the makefile you can change "pip install" to "pip -v install" to
see the details of the linking command.

**Comment by ahbarnett** [comment]
Glad it worked. @lu1and10 should this duplicate_lib thing be added to the mac makefiles, or the mac docs - could you handle that? Thks, Alex

**Comment by lu1and10** [comment]
> Glad it worked. @lu1and10 should this duplicate_lib thing be added to the mac makefiles, or the mac docs - could you handle that? Thks, Alex

Sure, I will do it.

**Comment by ahbarnett** [comment]
mac make.inc.* and docs/install.rst should explain this now for v2.0
