### ISSUE TITLE
finufft very slow on cluster machine

### ISSUE THREAD

**Issue by Sketos** [flatironinstitute/finufft#70]
Hi,

 I have installed finufft on a cluster machine, but for some reason the same script runs ~500 slower on the cluster than it does on my laptop (~5000 non-uniform points repeated 30 times).

 I am trying to understand what the reason might be. Starting from scratch, I have done the following:

 **i) cloned the GitHub repo**
 
 **ii) executed "make test" (took ~2mins; see output at the end). ** 

 **iii) executed "make lib" **
 
**Terminal output:**

 echo "lib-static/libfinufft.a and lib/libfinufft.so built, multithreaded versions"
 lib-static/libfinufft.a and lib/libfinufft.so built, multithreaded versions

 **iv) executed "pip -v install ." (see output at the end)**

After these steps I could import and use finufft, but as mentioned before the run speeds are surprisingly slow.

The loaded modules are:

1) python/3.6.5   
2) intel_comp/2018   
3) openmpi/3.0.1 
4) fftw/3.3.7

**Terminal output from "make test":**

test/finufft1d_basicpassfail
(cd test; \
export FINUFFT_REQ_TOL=1e-12; \
export FINUFFT_CHECK_TOL=1e-11; \
./check_finufft.sh)
numdiff not installed
FINUFFT library check at requested accuracy 1e-12 ...
Test number 1: testutils
next235even(90) =	90
next235even(91) =	96
next235even(92) =	96
next235even(93) =	96
next235even(94) =	96
next235even(95) =	96
next235even(96) =	96
next235even(97) =	100
next235even(98) =	100
next235even(99) =	100
completed

Test number 2: check1d.sh
test 1d type-1:
one mode: rel err in F[370] is 6.28e-13
dirft1d: rel l2-err of result F is 1.66e-12
test 1d type-2:
one targ: rel err in c[500] is 5.16e-13
dirft1d: rel l2-err of result c is 1.64e-12
test 1d type-3:
one targ: rel err in F[500] is 8.82e-13
dirft1d: rel l2-err of result F is 2.14e-12
completed

Test number 3: check2d.sh
test 2d type-1:
one mode: rel err in F[37,2] is 5.62e-13
dirft2d: rel l2-err of result F is 1.6e-12
test 2d type-2:
one targ: rel err in c[500] is 4.69e-13
dirft2d: rel l2-err of result c is 1.68e-12
test 2d type-3:
one targ: rel err in F[500] is 3.94e-13
dirft2d: rel l2-err of result F is 2.6e-12
test 2dmany type-1:
one mode: rel err in F[37,2] of data[5] is 9.15e-13
err check vs non-many: sup ( ||F_many-F||_2 / ||F||_2  ) =  2.68e-16
test 2dmany type-2:
one targ: rel err in c[500] of data[5] is 5.76e-14
err check vs non-many: sup ( ||c_many-c||_2 / ||c||_2 ) =  0
completed

Test number 4: check3d.sh
test 3d type-1:
one mode: rel err in F[1,2,-7] is 7.3e-13
dirft3d: rel l2-err of result F is 1.17e-12
test 3d type-2:
one targ: rel err in c[500] is 5.57e-13
dirft3d: rel l2-err of result c is 1.14e-12
test 3d type-3:
one targ: rel err in F[500] is 1.8e-13
dirft3d: rel l2-err of result F is 2.94e-12
completed

Test number 5: dumbinputs
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
nf1=4e+12 exceeds MAX_NF of 1e+11
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
nf1*nf2=1.6e+14 exceeds MAX_NF of 1e+11
ndata should be at least 1 (ndata=0)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
ndata should be at least 1 (ndata=0)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
setup_spreader: error, requested eps (0) is too small (<5.5e-17)
nf1*nf2*nf3=6.5e+15 exceeds MAX_NF of 1e+11
1D dumb cases ----------------
1d1 tol=0:	ier=1 (should complain)
1d1 N=0:	ier=0
1d1 M=0:	ier=0	nrm(F)=0 (should vanish)
1d2 tol=0:	ier=1 (should complain)
1d2 N=0:	ier=0	nrm(c)=0 (should vanish)
1d2 M=0:	ier=0
1d3 tol=0:	ier=1 (should complain)
1d3 nk=0:	ier=0
1d3 M=0:	ier=0	nrm(F)=0 (should vanish)
1d3 M=1:	ier=0	nrm(err)=0.0000
1d3 N=1:	ier=0	err=0.0000
1d3 M=N=1:	ier=0	err=0.0000
1d3 XK prod too big:	ier=2 (should complain)
2D dumb cases ----------------
2d1 tol=0:	ier=1 (should complain)
2d1 Ns=Nt=0:	ier=0
2d1 Ns=0,Nt>0:	ier=0
2d1 Ns>0,Ns=0:	ier=0
2d1 M=0:	ier=0	nrm(F)=0 (should vanish)
2d2 tol=0:	ier=1 (should complain)
2d2 Ns=Nt=0:	ier=0	nrm(c)=0 (should vanish)
2d2 Ns=0,Nt>0:	ier=0	nrm(c)=0 (should vanish)
2d2 Ns>0,Nt=0:	ier=0	nrm(c)=0 (should vanish)
2d2 M=0:	ier=0
2d3 tol=0:	ier=1 (should complain)
2d3 nk=0:	ier=0
2d3 M=0:	ier=0	nrm(F)=0 (should vanish)
2d3 M=1:	ier=0	nrm(F)=3.16
2d3 XK prod too big:	ier=2 (should complain)
2d1many ndata=0:	ier=9 (should complain)
2d1many tol=0:		ier=1 (should complain)
2d1many Ns=Nt=0:	ier=0
2d1many Ns=0,Nt>0:	ier=0
2d1many Ns>0,Ns=0:	ier=0
2d1many M=0:		ier=0	nrm(Fm)=0 (should vanish)
2d2many ndata=0:	ier=9 (should complain)
2d2many tol=0:		ier=1 (should complain)
2d2many Ns=Nt=0:	ier=0	nrm(cm)=0 (should vanish)
2d2many Ns=0,Nt>0:	ier=0	nrm(cm)=0 (should vanish)
2d2many Ns>0,Nt=0:	ier=0	nrm(cm)=0 (should vanish)
2d2many M=0:		ier=0
3D dumb cases ----------------
3d1 tol=0:	ier=1 (should complain)
3d1 Ns=Nt=Nu=0:	ier=0
3d1 Ns,Nt>0,Nu=0:	ier=0
3d1 Ns>0,Nt=0,Nu>0:	ier=0
3d1 Ns,Nt>0,Nu=0:	ier=0
3d1 M=0:	ier=0	nrm(F)=0 (should vanish)
3d2 tol=0:	ier=1 (should complain)
3d2 Ns=Nt=Nu=0:	ier=0	nrm(c)=0 (should vanish)
3d2 Ns=0,Nt,Nu>0:	ier=0	nrm(c)=0 (should vanish)
3d2 Ns>0,Nt=0,Nu>0:	ier=0	nrm(c)=0 (should vanish)
3d2 Ns,Nt>0,Nu=0:	ier=0	nrm(c)=0 (should vanish)
3d2 M=0:	ier=0
3d3 tol=0:	ier=1 (should complain)
3d3 nk=0:	ier=0
3d3 M=0:	ier=0	nrm(F)=0 (should vanish)
3d3 M=1:	ier=0	nrm(F)=3.16
3d3 XK prod too big:	ier=2 (should complain)
freed.
completed

0 crashes out of 5 tests done
Please check by eye that the numerical output has errors at expected level!
(or install numdiff and rerun; see ../INSTALL.md)

**Terminal output from "pip -v install .":**

Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-bh_wkunq
Created temporary directory: /tmp/pip-req-tracker-a7lermto
Initialized build tracking at /tmp/pip-req-tracker-a7lermto
Created build tracker: /tmp/pip-req-tracker-a7lermto
Entered build tracker: /tmp/pip-req-tracker-a7lermto
Created temporary directory: /tmp/pip-install-ewmn93qv
Processing /cosma/home/durham/dc-amvr1/MyProjects/UVgalpak3D/modules/finufft
  Created temporary directory: /tmp/pip-req-build-cwsz_eog
  Added file:///cosma/home/durham/dc-amvr1/MyProjects/UVgalpak3D/modules/finufft to build tracker '/tmp/pip-req-tracker-a7lermto'
    Running setup.py (path:/tmp/pip-req-build-cwsz_eog/setup.py) egg_info for package from file:///cosma/home/durham/dc-amvr1/MyProjects/UVgalpak3D/modules/finufft
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info
    writing /tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/requires.txt
    writing top-level names to /tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-req-build-cwsz_eog/pip-egg-info/finufftpy.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-cwsz_eog has version 1.1.2, which satisfies requirement finufftpy==1.1.2 from file:///cosma/home/durham/dc-amvr1/MyProjects/UVgalpak3D/modules/finufft
  Removed finufftpy==1.1.2 from file:///cosma/home/durham/dc-amvr1/MyProjects/UVgalpak3D/modules/finufft from build tracker '/tmp/pip-req-tracker-a7lermto'
Requirement already satisfied: numpy in /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages (from finufftpy==1.1.2) (1.18.2)
Requirement already satisfied: pybind11>=2.2 in /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages (from finufftpy==1.1.2) (2.5.0)
Installing collected packages: finufftpy
  Attempting uninstall: finufftpy
    Found existing installation: finufftpy 1.1.2
    Uninstalling finufftpy-1.1.2:
      Created temporary directory: /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/~inufftpy-1.1.2-py3.6.egg-info
      Removing file or directory /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy-1.1.2-py3.6.egg-info
      Created temporary directory: /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/~inufftpy
      Removing file or directory /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy/
      Created temporary directory: /tmp/pip-uninstall-8a00tln6
      Removing file or directory /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy_cpp.cpython-36m-x86_64-linux-gnu.so
      Successfully uninstalled finufftpy-1.1.2
  Created temporary directory: /tmp/pip-record-j45glgwb
    Running command /cosma/home/durham/dc-amvr1/enviroments/generic_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-cwsz_eog/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-cwsz_eog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j45glgwb/install-record.txt --single-version-externally-managed --compile --install-headers /cosma/home/durham/dc-amvr1/enviroments/generic_env/include/site/python3.6/finufftpy
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/finufftpy
    copying finufftpy/__init__.py -> build/lib.linux-x86_64-3.6/finufftpy
    copying finufftpy/_interfaces.py -> build/lib.linux-x86_64-3.6/finufftpy
    running build_ext
    creating tmp
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -idirafter /usr/include/linux -I/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/pstl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/include -I/cosma/local/gcc/7.3.0/include -I/cosma/local/Python/3.6.5/lib/python3.6/site-packages/numpy/core/include/ -I/cosma/local/Python/3.6.5/include/python3.6m/ -I/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/include -fPIC -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/include -I/cosma/local/Python/3.6.5/include/python3.6m -c /tmp/tmp_0svnw3b.cpp -o tmp/tmp_0svnw3b.o -std=c++14
    gcc: error: unrecognized command line option ‘-std=c++14’
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -idirafter /usr/include/linux -I/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/pstl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/include -I/cosma/local/gcc/7.3.0/include -I/cosma/local/Python/3.6.5/lib/python3.6/site-packages/numpy/core/include/ -I/cosma/local/Python/3.6.5/include/python3.6m/ -I/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/include -fPIC -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/include -I/cosma/local/Python/3.6.5/include/python3.6m -c /tmp/tmp18gjwvp6.cpp -o tmp/tmp18gjwvp6.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -idirafter /usr/include/linux -I/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/pstl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/include -I/cosma/local/gcc/7.3.0/include -I/cosma/local/Python/3.6.5/lib/python3.6/site-packages/numpy/core/include/ -I/cosma/local/Python/3.6.5/include/python3.6m/ -I/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/include -fPIC -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/include -I/cosma/local/Python/3.6.5/include/python3.6m -c /tmp/tmp4l4pad9h.cpp -o tmp/tmp4l4pad9h.o -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    building 'finufftpy_cpp' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/finufftpy
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -idirafter /usr/include/linux -I/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/pstl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/include -I/cosma/local/gcc/7.3.0/include -I/cosma/local/Python/3.6.5/lib/python3.6/site-packages/numpy/core/include/ -I/cosma/local/Python/3.6.5/include/python3.6m/ -I/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/include -fPIC -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/pybind11/include -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/pybind11/include -Isrc -I/cosma/home/durham/dc-amvr1/enviroments/generic_env/include -I/cosma/local/Python/3.6.5/include/python3.6m -c finufftpy/finufftpy.cpp -o build/temp.linux-x86_64-3.6/finufftpy/finufftpy.o -DVERSION_INFO="1.1.2" -std=c++11 -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared -L/cosma/local/gcc/7.3.0/lib64/ -Wl,-rpath=/cosma/local/gcc/7.3.0/lib64/ -L/cosma/local/gcc/7.3.0/lib64/ -Wl,-rpath=/cosma/local/gcc/7.3.0/lib64/ -L/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/lib -Wl,-rpath=/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/lib -Wl,-rpath=/cosma/local/openmpi/intel_2018/3.0.1/lib -L/cosma/local/Intel/Parallel_Studio_XE_2018/debugger_2018/libipt/intel64/lib -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/debugger_2018/libipt/intel64/lib -L/cosma/local/Intel/Parallel_Studio_XE_2018/debugger_2018/iga/lib -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/debugger_2018/iga/lib -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7 -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7 -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64 -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64 -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4 -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4 -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin -L/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64 -Wl,-rpath=/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64 -L/cosma/local/gcc/7.3.0/lib64 -Wl,-rpath=/cosma/local/gcc/7.3.0/lib64 -L/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/lib -Wl,-rpath=/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/lib -idirafter /usr/include/linux -I/cosma/local/fftw//intel_2018_ompi_3.0.1/3.3.7/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/daal/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/tbb/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/pstl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/mkl/include -I/cosma/local/Intel/Parallel_Studio_XE_2018/compilers_and_libraries_2018.2.199/linux/ipp/include -I/cosma/local/gcc/7.3.0/include -I/cosma/local/Python/3.6.5/lib/python3.6/site-packages/numpy/core/include/ -I/cosma/local/Python/3.6.5/include/python3.6m/ -I/cosma/local/fftw//intel_2020_intel_mpi_2020/3.3.7/include build/temp.linux-x86_64-3.6/finufftpy/finufftpy.o -L/cosma/local/Python/3.6.5/lib lib-static/libfinufft.a -lfftw3 -lfftw3_omp -lgomp -lpython3.6m -o build/lib.linux-x86_64-3.6/finufftpy_cpp.cpython-36m-x86_64-linux-gnu.so
    running install_lib
    creating /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy
    copying build/lib.linux-x86_64-3.6/finufftpy/__init__.py -> /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy
    copying build/lib.linux-x86_64-3.6/finufftpy/_interfaces.py -> /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy
    copying build/lib.linux-x86_64-3.6/finufftpy_cpp.cpython-36m-x86_64-linux-gnu.so -> /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages
    byte-compiling /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy/__init__.py to __init__.cpython-36.pyc
    byte-compiling /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy/_interfaces.py to _interfaces.cpython-36.pyc
    running install_egg_info
    running egg_info
    creating finufftpy.egg-info
    writing finufftpy.egg-info/PKG-INFO
    writing dependency_links to finufftpy.egg-info/dependency_links.txt
    writing requirements to finufftpy.egg-info/requires.txt
    writing top-level names to finufftpy.egg-info/top_level.txt
    writing manifest file 'finufftpy.egg-info/SOURCES.txt'
    reading manifest file 'finufftpy.egg-info/SOURCES.txt'
    writing manifest file 'finufftpy.egg-info/SOURCES.txt'
    Copying finufftpy.egg-info to /cosma/home/durham/dc-amvr1/enviroments/generic_env/lib/python3.6/site-packages/finufftpy-1.1.2-py3.6.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-record-j45glgwb/install-record.txt'
    Running setup.py install for finufftpy ... done
Successfully installed finufftpy-1.1.2
Cleaning up...
  Removing source in /tmp/pip-req-build-cwsz_eog
Removed build tracker: '/tmp/pip-req-tracker-a7lermto'

**Comment by ahbarnett** [comment]
Hi Stekos,
This is weird. "make test" should take say 10 secs of compilation, <1 sec to run.
When you say " a cluster machine", can you be specific (do you mean the Flatiron cluster?). How many cores? How many NU pts/sec are you seeing?
Try lowering the OMP_NUM_THREADS to <=12 and report back.

Here's typ timing on older 14-core node:
model name	: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

OMP_NUM_THREADS=28 test/finufft3d_test 1e2 1e2 1e2 1e7 1e-6
test 3d type-1:
     10000000 NU pts to (100,100,100) modes in 0.484 s 	2.06e+07 NU pts/s
one mode: rel err in F[37,26,-39] is 1.82e-08
test 3d type-2:
     (100,100,100) modes to 10000000 NU pts in 0.433 s 	2.31e+07 NU pts/s
one targ: rel err in c[5000000] is 1.96e-07
test 3d type-3:
	10000000 NU to 1000000 NU in 3.34 s         	3.29e+06 tot NU pts/s
one targ: rel err in F[500000] is 1.13e-07

OMP_NUM_THREADS=1 test/finufft3d_test 1e2 1e2 1e2 1e7 1e-6
test 3d type-1:
     10000000 NU pts to (100,100,100) modes in 5.24 s 	1.91e+06 NU pts/s
one mode: rel err in F[37,26,-39] is 1.44e-07
test 3d type-2:
     (100,100,100) modes to 10000000 NU pts in 8.21 s 	1.22e+06 NU pts/s
one targ: rel err in c[5000000] is 2.34e-07
test 3d type-3:
	10000000 NU to 1000000 NU in 11.3 s         	9.69e+05 tot NU pts/s
one targ: rel err in F[500000] is 2.93e-07

**Comment by ahbarnett** [comment]
PS if you *do* mean the Flatiron cluster, if you log in directly to a node it throttles CPU usage by a factor of 100 or so. You need to use slurm to request a node. Is that your problem? Alex

**Comment by Sketos** [comment]
I am executing it on COSMA (https://www.dur.ac.uk/icc/cosma/). However, I only tried executing it on the login node not submitting a batch job using slurm. I will try that now cause I might be experiencing the same issue that you just mentioned.

**Comment by Sketos** [comment]
simply using slurm to submit the job didn't make a huge difference (~5000 points, repeated 32 times; ~10sec), but using "export OMP_NUM_THREADS=1" I am now getting similar runtimes as on my laptop (~5000 points, repeated 32 times; ~0.03sec).

Both tests use 1 node.

Thank you very much for your help!

**Comment by ahbarnett** [comment]
Hi Stekos, that is weird. Up to say 12 threads you should still get a decent xeon speedup (see our SISC 2019 paper). Let me know if still an issue for you.
