### ISSUE TITLE
Compiling flag unknown gcc

### ISSUE THREAD

**Issue by hbrunie** [flatironinstitute/finufft#75]
Hi,

Concerning -march=native in makefile I got the compile error:
the flag -march has been replaced by -mcpu in gcc since around 5.0 (I don't know which version exactly, but gcc/4.8.5 is with -march and gcc/5.4.0 is with -mcpu)

I found an answer in https://stackoverflow.com/questions/5188267/checking-the-gcc-version-in-a-makefile

a way to test for version number is:
GCC_VERSION := $(shell gcc -dumpversion) #here using := and not = is important.
VERSION := 5.0.0
ifeq ($(VERSION),$(firstword $(sort $(GCC_VERSION) $(VERSION)))) 
    CFLAGS   = -fPIC -O3 -funroll-loops -mcpu=native -fcx-limited-range
else
    CFLAGS   = -fPIC -O3 -funroll-loops -march=native -fcx-limited-range
endif

Best regards,
 Hugo

**Comment by ahbarnett** [comment]
Dear Hugo, I'm a bit confused, since in GCC current docs -march is very much alive and well. Eg see:
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
In fact, it is -mcpu that is deprecated.
Can you list your system details? And where you're getting your info on GCC?   Thanks, Alex

**Comment by hbrunie** [comment]
Dear Alex,
indeed this very confusing.
I made an assumption about the change in gcc flags only based on the experience of this not working in my context, which was a mistake. You are totally right about mcpu being deprecated and march being alive and well.

And this makes it very confusing because I got:

[hbrunie@login3.summit finufft]$ make test
g++ -fPIC -O3 -funroll-loops -march=native -fcx-limited-range -I src -fopenmp -DNEED_EXTERN_C -fopenmp test/finufft2d_test.cpp src/spreadinterp.o src/utils.o src/finufft2d.o src/dirft2d.o src/common.o contrib/legendre_rule_fast.o -lfftw3 -lm  -lfftw3_omp  -o test/finufft2d_test
g++: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
make: *** [test/finufft2d_test] Error 1
[hbrunie@login3.summit finufft]$ g++ --version
g++ (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Would you have any highlight for me?
Thanks,
Best,

**Comment by hbrunie** [comment]
Ok,
If it is still the case https://github.com/mfem/mfem/issues/216
It seems like -march=native is not supported on power PC and:
head /proc/cpuinfo 
processor	: 0
cpu		: POWER9, altivec supported
clock		: 3800.000000MHz
revision	: 2.1 (pvr 004e 1201)

In this case, -mtune or -mcpu native should be used.
These are also supported: https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc.pdf page 249

**Comment by ahbarnett** [comment]
Ok, great. If you make an example make.inc.power9 that replaces CFLAGS, I'll add it to the repo. Thanks! Alex

**Comment by hbrunie** [comment]
Hi Alex,
I suggested a pull request with a make.inc.power9.
Actually it could be called make.inc.powerpc, and could be updated if people test it on other powerpc.
I got inspired from AMReX project GNUMakefile tools. They have a very complete set of files for this :).

Cheers,
 Hugo
