### ISSUE TITLE
combined double & single prec support, with language interfaces

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#83]
Long-term we'd want the python, say, call to check the type of inputs, and call different
C++ libraries if single vs double precision.
Currently although these two libs have distinct names (libfinufft vs libfinufftf) the *namespaces* coincide (finufft_makeplan, etc), so it is impossible to do this.
The user has to choose which to build, and the py pkg is double-prec only.
Now, the speed difference is small, so the main reason would be RAM (single copying to double before the call  = 3x RAM, plus 2x in most of FINUFFT's internal workings).
The best would be C++ templating - Andrea prototyped this already in summer 2019. We need to think about how to do this, probably post version 1.2.
I am not experienced in this. Thoughts?

**Comment by garrettwrong** [comment]
Linking with PR #94 .

Once that (or something equivalent) is in, we can build off it to close out this issue.

**Comment by ahbarnett** [comment]
Library and headers are all dual-prec.
MATLAB/octave dual-prec are now done and tested in guruInterface_v2.

**Comment by ahbarnett** [comment]
THis is now all done as of 277b69a
