### ISSUE TITLE
"omp_set_nested routine deprecated, please use omp_set_max_active_levels instead."

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#88]
new warning using ICC 2020.

we need to figure out how to count "active levels".
THen, fix:
in master:    src/finufft2d.cpp
in gi_v2: src/finufft.cpp

**Comment by lu1and10** [comment]
Seems this is still compiler dependent, different implementation of omp lib
has different behavior now.

I tested the following code with different results as the following.
For gcc, we still need to call omp_set_nested to enable nested,
omp_set_max_active_levesl does not have control of enabling nested or not.
While for icc, omp_set_max_active_levels has control of enabling nested or
not.

------------------------------------------------------
------------------------------------------------------
---------------------------
#include <omp.h>
#include <stdio.h>
#include <iostream>
void report_num_threads(int level)
{
    #pragma omp single
    {
        printf("Level %d: number of threads in the team - %d\n",
                  level, omp_get_num_threads());
    }
 }
int main()
{
    std::cout<<"nested: "<<omp_get_nested()<<"\n";
    omp_set_max_active_levels(3);
    std::cout<<"nested: "<<omp_get_nested()<<"\n";
    omp_set_dynamic(0);
    #pragma omp parallel num_threads(2)
    {
        report_num_threads(1);
        #pragma omp parallel num_threads(2)
        {
            report_num_threads(2);
            #pragma omp parallel num_threads(2)
            {
                report_num_threads(3);
            }
        }
    }
    return(0);
}
------------------------------------------------------
------------------------------------------------------
---------------------------
intel icpc result:
----------------
OMP: Info #274: omp_get_nested routine deprecated, please use
omp_get_max_active_levels instead.
nested: 0
OMP: Info #274: omp_get_nested routine deprecated, please use
omp_get_max_active_levels instead.
nested: 1
Level 1: number of threads in the team - 2
Level 2: number of threads in the team - 2
Level 2: number of threads in the team - 2
Level 3: number of threads in the team - 2
Level 3: number of threads in the team - 2
Level 3: number of threads in the team - 2
Level 3: number of threads in the team - 2
------------------------------------------------------
------------------------------------------------------
---------------------------
gcc 9.3 result:
---------------
nested: 0
nested: 0
Level 1: number of threads in the team - 2
Level 2: number of threads in the team - 1
Level 2: number of threads in the team - 1
Level 3: number of threads in the team - 1
Level 3: number of threads in the team - 1

**Comment by ahbarnett** [comment]
That's upsetting. Thanks for checking!
I guess we have to live with the warning for now, then? Lots of others online will have the same issue.
Might be a qurestion for our people at SCC (once the water issue dies down!).
Of course an ugly solution is to add a compiler flag -Domp_has_nested and #ifdef in code.

**Comment by ahbarnett** [comment]
BTW did you find out if the outer par block is 1-thread, whether if nesting off (or levels=1), and inner par block starts many threads?

**Comment by lu1and10** [comment]
Seems libgomp is still on openmp 4.5 specification, in openmp
5.0 Specification omp_set_nested becomes deprecated.

For levels=1, i.e., nesting is off; the outer most par block is many
threads, inner par blocks is 1 thread.

**Comment by ahbarnett** [comment]
What I meant is if num_threads(1) is used in the outer, does this allow many threads in the inner?

But I realised it doesn't matter, because we control it properly here in finufft.cpp:

 ```
 MY_OMP_SET_NESTED(p->opts.spread_thread!=2);
  int nthr_outer = p->opts.spread_thread==1 ? 1 : batchSize;
  
#pragma omp parallel for num_threads(nthr_outer)
```
See nufft_opts.h for explanation of the opts.

**Comment by lu1and10** [comment]
I see.
For curiosity, I tested.
If the outer is num_threads(1), and max_levels=1, the inner par block will
get many threads. Basically the outer most block with num_threads > 1 will
get parallelized in the nested mode.

**Comment by lu1and10** [comment]
Even if it's not in nested mode, it will still parallelize the first para
block with num_threads>1.

**Comment by ahbarnett** [comment]
THanks for checking - that's what I'd suspected. It means for spread_thread=1 we could actually leave set_nested(0). The only case that needs nesting is spread_thread=3, and I'm pretty confident that is never faster than the better of 1 and 2.
If you want to run some timings to verify this,
test/finufftGuru_test 10 1 2 1e3 1e3 0 1e6 1e-9 0 s
where s=1,2,3
for larger probs, or
test/finufftGuru_test 1000 1 2 1e2 1e2 0 1e4 1e-9 0 s
for smaller ones.
Try various sizes, dimensions, etc.  I only tried on the i7, not the xeon.

So one option is kill spread_thread=3 and never use nesting. But it would be nice to have the option to explore here.
