### ISSUE TITLE
gi_v2 OMP=OFF minor oversight

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/finufft#98]
Some of the `fortran` examples have hardcoded OMP methods.  They break things upon running `make OMP=OFF fortran` on my machine.  The method in question is `omp_get_wtime`.  You might replace it with code that uses system clock or something for single threaded use, or just stub/def it out.  For debugging it is useful to have single threaded without going into the code to comment them out; that is how I found it...

**Comment by ahbarnett** [comment]
good idea - will do.
(BTW when you said some other dev did f interfaces, yes, the nufft?d_demo*.f tests were inherited from CMCL. But I did the simple1d1 etc so am responsible for using omp_get_wtime).
